import {Component,OnInit,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {finalize} from 'rxjs';
import {NoveltyDetail} from '../../core/models/novelty.models';
import {NoveltyService} from '../../core/services/novelty.service';
import {AuthService} from '../../core/services/auth.service';
import {apiErrorMessage} from '../../shared/api-error';
@Component({standalone:true,imports:[FormsModule],template:`
<section class="page-header"><div><p class="eyebrow">Novedades</p><h1>Detalle de novedad</h1><p class="muted">Seguimiento, soportes e historial.</p></div></section>
@if(error()){<div class="alert error">{{error()}}</div>} @if(success()){<div class="alert success">{{success()}}</div>}
@if(data();as d){<section class="panel"><div class="panel-heading"><div><h2>{{d.novelty.tipo_novedad}} · {{d.novelty.nombre_completo}}</h2><span class="badge">{{d.novelty.estado}}</span></div><div class="row-actions">
@if(auth.hasPermission('NOVEDADES_EDITAR')&&editable()){<button class="btn secondary" (click)="editing.set(!editing())">{{editing()?'Cancelar':'Editar'}}</button>}
@if(auth.hasPermission('NOVEDADES_CAMBIAR_ESTADO')&&d.novelty.estado!=='ANULADA'){<select class="status-select" [(ngModel)]="newStatus"><option>REGISTRADA</option><option>VALIDADA</option><option>CERRADA</option><option>ANULADA</option></select><button class="btn primary" (click)="changeStatus()">Confirmar estado</button>}</div></div>
@if(editing()){<form class="form-grid" (ngSubmit)="saveEdit()"><label>Fecha inicio<input type="date" name="start" [(ngModel)]="edit.start_date"></label><label>Fecha fin<input type="date" name="end" [(ngModel)]="edit.end_date"></label>@if(d.novelty.es_incapacidad){<label>Diagnóstico<input name="diagnosis" [(ngModel)]="edit.diagnosis"></label><label>CIE-10<input name="cie" [(ngModel)]="edit.cie10_code"></label><label>Origen<input name="origin" [(ngModel)]="edit.origin"></label><label>Certificado<input name="cert" [(ngModel)]="edit.certificate_number"></label>}@else{<label class="form-wide">Motivo<input name="reason" [(ngModel)]="edit.reason"></label>}<label class="form-wide">Observaciones<textarea name="obs" [(ngModel)]="edit.observations"></textarea></label><div class="form-actions form-wide"><button class="btn primary" [disabled]="busy()">Guardar</button></div></form>}@else{<dl><dt>Documento</dt><dd>{{d.novelty.numero_documento}}</dd><dt>Periodo</dt><dd>{{d.novelty.fecha_inicio}} a {{d.novelty.fecha_fin||'sin fecha final'}} ({{d.novelty.numero_dias}} días)</dd><dt>Motivo / diagnóstico</dt><dd>{{d.novelty.diagnostico||d.novelty.motivo||'—'}}</dd><dt>EPS</dt><dd>{{d.novelty.eps||'—'}}</dd><dt>Origen</dt><dd>{{d.novelty.origen_incapacidad||'—'}}</dd><dt>Observaciones</dt><dd>{{d.novelty.observaciones||'—'}}</dd></dl>}</section>
<section class="detail-grid"><article class="panel"><h2>Soportes</h2>@for(e of d.evidence;track e.id_novedad_evidencia){<div class="role-item"><div><strong>{{e.nombre_archivo}}</strong><small>{{e.tipo_evidencia}} · {{e.created_at}}</small></div>@if(e.archivo_url_publica){<a class="btn small ghost" target="_blank" rel="noopener" [href]="e.archivo_url_publica">Abrir</a>}</div>}@empty{<p class="empty compact">Sin soportes.</p>}
@if(auth.hasPermission('NOVEDADES_SOPORTES')&&d.novelty.estado!=='ANULADA'){<form class="drawer-section" (ngSubmit)="addEvidence()"><label>Tipo<select name="evtype" [(ngModel)]="evidence.type"><option>SOPORTE</option><option>TRANSCRIPCION</option><option>PRORROGA</option><option>OTRO</option></select></label><label>Nombre<input required name="evname" [(ngModel)]="evidence.name"></label><label>URL externa<input name="evurl" [(ngModel)]="evidence.url" [disabled]="!!evidence.file"></label><label>Archivo<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" (change)="pick($event)" [disabled]="!!evidence.url"></label><button class="btn primary" [disabled]="busy()">Agregar soporte</button></form>}</article>
<article class="panel"><h2>Historial</h2>@for(h of d.history;track h.id_novedad_historial){<div class="role-item"><div><strong>{{h.accion}}</strong><small>{{h.created_at}} · {{h.nombre_usuario}}</small><p>{{h.detalle||'Sin detalle'}}</p>@if(h.estado_nuevo){<small>{{h.estado_anterior||'—'}} → {{h.estado_nuevo}}</small>}</div></div>}@empty{<p class="empty compact">Sin historial.</p>}</article></section>}`})
export class NoveltyDetailComponent implements OnInit{readonly auth=inject(AuthService);private api=inject(NoveltyService);private route=inject(ActivatedRoute);private id=0;data=signal<NoveltyDetail|null>(null);error=signal('');success=signal('');busy=signal(false);editing=signal(false);newStatus='VALIDADA';edit:any={};evidence:any={type:'SOPORTE',name:'',url:'',file:null};ngOnInit(){this.id=Number(this.route.snapshot.paramMap.get('id'));this.load();}editable(){return !['CERRADA','ANULADA'].includes(this.data()?.novelty.estado||'');}load(){this.api.get(this.id).subscribe({next:d=>{this.data.set(d);this.newStatus=d.novelty.estado;this.edit={start_date:d.novelty.fecha_inicio,end_date:d.novelty.fecha_fin||'',reason:d.novelty.motivo||'',observations:d.novelty.observaciones||'',diagnosis:d.novelty.diagnostico||'',cie10_code:d.novelty.codigo_cie10||'',origin:d.novelty.origen_incapacidad||'ENFERMEDAD_GENERAL',certificate_number:d.novelty.numero_certificado||'',eps_id:(d.novelty as any).id_eps??null,is_extension:!!d.novelty.es_prorroga,source_disability_id:d.novelty.id_incapacidad_origen,filing_date:d.novelty.fecha_radicacion};},error:e=>this.error.set(apiErrorMessage(e,'No fue posible cargar la novedad.'))});}changeStatus(){let o='';if(this.newStatus==='ANULADA'){o=prompt('Motivo de anulación:')?.trim()||'';if(!o){this.error.set('El motivo es obligatorio.');return;}}this.run(this.api.status(this.id,this.newStatus,o),'Estado actualizado.');}saveEdit(){const n=this.data()!.novelty;this.run(n.es_incapacidad?this.api.updateDisability(this.id,{...this.edit,employee_id:n.id_empleado,end_date:this.edit.end_date}):this.api.update(this.id,this.edit),'Novedad actualizada.');}pick(e:Event){this.evidence.file=(e.target as HTMLInputElement).files?.[0]||null;}addEvidence(){if(!this.evidence.name||(!this.evidence.url&&!this.evidence.file)){this.error.set('Indica nombre y URL o archivo.');return;}this.run(this.api.addEvidence(this.id,{evidence_type:this.evidence.type,file_name:this.evidence.name,file_url:this.evidence.url,file:this.evidence.file}),'Soporte agregado.');}private run(o:any,m:string){this.busy.set(true);this.error.set('');o.pipe(finalize(()=>this.busy.set(false))).subscribe({next:()=>{this.success.set(m);this.editing.set(false);this.load();},error:(e:any)=>this.error.set(apiErrorMessage(e,'No fue posible completar la operación.'))});}}
