INSERT INTO BBF_PERMISOS (CODIGO, NOMBRE, DESCRIPCION, MODULO, ACTIVO, FECHA_CREACION)
SELECT 'DEVOLUCIONES_VER', 'Ver devoluciones', 'Permite listar y consultar devoluciones', 'DEVOLUCIONES', 1, NOW()
WHERE NOT EXISTS (SELECT 1 FROM BBF_PERMISOS WHERE CODIGO = 'DEVOLUCIONES_VER');

INSERT INTO BBF_PERMISOS (CODIGO, NOMBRE, DESCRIPCION, MODULO, ACTIVO, FECHA_CREACION)
SELECT 'DEVOLUCIONES_CREAR', 'Crear devoluciones', 'Permite consultar disponibles y registrar devoluciones', 'DEVOLUCIONES', 1, NOW()
WHERE NOT EXISTS (SELECT 1 FROM BBF_PERMISOS WHERE CODIGO = 'DEVOLUCIONES_CREAR');

INSERT INTO BBF_PERMISOS (CODIGO, NOMBRE, DESCRIPCION, MODULO, ACTIVO, FECHA_CREACION)
SELECT 'DEVOLUCIONES_CONFIRMAR', 'Confirmar devoluciones', 'Permite confirmar devoluciones registradas', 'DEVOLUCIONES', 1, NOW()
WHERE NOT EXISTS (SELECT 1 FROM BBF_PERMISOS WHERE CODIGO = 'DEVOLUCIONES_CONFIRMAR');

INSERT INTO BBF_PERMISOS (CODIGO, NOMBRE, DESCRIPCION, MODULO, ACTIVO, FECHA_CREACION)
SELECT 'DEVOLUCIONES_ANULAR', 'Anular devoluciones', 'Permite anular devoluciones conservando trazabilidad', 'DEVOLUCIONES', 1, NOW()
WHERE NOT EXISTS (SELECT 1 FROM BBF_PERMISOS WHERE CODIGO = 'DEVOLUCIONES_ANULAR');
