-- Correccion minima posterior a 260803_capacitaciones_estructura_y_sp.sql
-- Evita borrar documento o firma al actualizar solamente el estado del compromiso.
USE `bbf_administrativo`;
DELIMITER $$
DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_LABORES_ASOCIADAS_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_LABORES_ASOCIADAS_LISTAR`(IN P_ID_CAPACITACION INT, IN P_INCLUIR_INACTIVAS TINYINT)
BEGIN
    SELECT D.ID_CAPACITACION_LABOR_DETALLE,D.ID_CAPACITACION,D.ID_CAPACITACION_LABOR,
    L.CODIGO,L.NOMBRE,L.DESCRIPCION,D.PUNTAJE_MINIMO_LABOR,D.PUNTAJE_MAXIMO_LABOR,
    D.ORDEN,D.ACTIVO
    FROM bbf_capacitacion_labor_detalle D
    INNER JOIN bbf_capacitacion_labores L ON L.ID_CAPACITACION_LABOR=D.ID_CAPACITACION_LABOR
    WHERE D.ID_CAPACITACION=P_ID_CAPACITACION
      AND (IFNULL(P_INCLUIR_INACTIVAS,0)=1 OR (D.ACTIVO=1 AND L.ACTIVO=1))
    ORDER BY D.ORDEN,L.ORDEN,L.NOMBRE;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_COMPROMISO_ACTUALIZAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_COMPROMISO_ACTUALIZAR`(
    IN P_ID_COMPROMISO INT, IN P_ESTADO VARCHAR(30), IN P_DOCUMENTO_URL VARCHAR(500),
    IN P_DOCUMENTO_RUTA VARCHAR(500), IN P_FIRMA_URL VARCHAR(500), IN P_OBSERVACIONES TEXT, IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_ESTADO VARCHAR(30); SET V_ESTADO=UPPER(TRIM(P_ESTADO));
    IF V_ESTADO NOT IN('BORRADOR','PENDIENTE_FIRMA','FIRMADO','CUMPLIDO','INCUMPLIDO','ANULADO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Estado de compromiso no valido.';
    END IF;
    IF NOT EXISTS(SELECT 1 FROM bbf_capacitacion_compromisos WHERE ID_CAPACITACION_COMPROMISO=P_ID_COMPROMISO) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El compromiso no existe.';
    END IF;
    UPDATE bbf_capacitacion_compromisos SET ESTADO=V_ESTADO,
    DOCUMENTO_URL=COALESCE(NULLIF(TRIM(P_DOCUMENTO_URL),''),DOCUMENTO_URL),
    DOCUMENTO_RUTA=COALESCE(NULLIF(TRIM(P_DOCUMENTO_RUTA),''),DOCUMENTO_RUTA),
    FIRMA_URL=COALESCE(NULLIF(TRIM(P_FIRMA_URL),''),FIRMA_URL),
    FECHA_FIRMA=CASE WHEN V_ESTADO IN('FIRMADO','CUMPLIDO','INCUMPLIDO') AND FECHA_FIRMA IS NULL THEN CURRENT_TIMESTAMP ELSE FECHA_FIRMA END,
    ID_CERRADO_POR=CASE WHEN V_ESTADO IN('CUMPLIDO','INCUMPLIDO','ANULADO') THEN P_ID_USUARIO ELSE ID_CERRADO_POR END,
    OBSERVACIONES=COALESCE(NULLIF(TRIM(P_OBSERVACIONES),''),OBSERVACIONES)
    WHERE ID_CAPACITACION_COMPROMISO=P_ID_COMPROMISO;
    SELECT * FROM bbf_capacitacion_compromisos WHERE ID_CAPACITACION_COMPROMISO=P_ID_COMPROMISO;
END$$

-- Expone el resultado y el compromiso en el detalle de la sesion para que
-- RRHH pueda iniciar el proceso directamente desde el participante no aprobado.
DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_SESION_DETALLE`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_SESION_DETALLE`(IN P_ID_SESION INT)
BEGIN
    SELECT S.*,C.NOMBRE AS CAPACITACION,C.TIPO,C.PUNTAJE_MINIMO,C.PUNTAJE_MAXIMO
    FROM bbf_capacitacion_sesiones S
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    WHERE S.ID_CAPACITACION_SESION=P_ID_SESION;

    SELECT P.*,E.NUMERO_DOCUMENTO,CONCAT_WS(' ',E.NOMBRES,E.APELLIDOS) AS EMPLEADO,E.ESTADO_EMPLEADO,
    R.ID_CAPACITACION_RESULTADO,R.TOTAL_ACUMULADO,R.PUNTAJE_FINAL,R.PUNTAJE_MINIMO_APLICADO,
    R.RESULTADO,R.REQUIERE_REINDUCCION,R.REQUIERE_COMPROMISO,
    CO.ID_CAPACITACION_COMPROMISO,CO.ESTADO AS ESTADO_COMPROMISO
    FROM bbf_capacitacion_participantes P
    INNER JOIN bbf_empleados E ON E.ID_EMPLEADO=P.ID_EMPLEADO
    LEFT JOIN bbf_capacitacion_resultados R ON R.ID_CAPACITACION_PARTICIPANTE=P.ID_CAPACITACION_PARTICIPANTE
    LEFT JOIN bbf_capacitacion_compromisos CO ON CO.ID_CAPACITACION_RESULTADO=R.ID_CAPACITACION_RESULTADO
    WHERE P.ID_CAPACITACION_SESION=P_ID_SESION
    ORDER BY E.NOMBRES,E.APELLIDOS;

    SELECT EV.*,L.CODIGO AS CODIGO_LABOR,L.NOMBRE AS LABOR,P.ID_EMPLEADO
    FROM bbf_capacitacion_evaluaciones EV
    INNER JOIN bbf_capacitacion_labores L ON L.ID_CAPACITACION_LABOR=EV.ID_CAPACITACION_LABOR
    INNER JOIN bbf_capacitacion_participantes P ON P.ID_CAPACITACION_PARTICIPANTE=EV.ID_CAPACITACION_PARTICIPANTE
    WHERE P.ID_CAPACITACION_SESION=P_ID_SESION
    ORDER BY P.ID_EMPLEADO,L.ORDEN,EV.FECHA_EVALUACION;
END$$

-- Incluye el resultado que origina la alerta y el compromiso ya creado.
-- Esto habilita la accion y evita presentar compromisos duplicados.
DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_ALERTAS_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_ALERTAS_LISTAR`(IN P_ID_EMPLEADO INT)
BEGIN
    SELECT 'EVALUACION_PENDIENTE' AS TIPO_ALERTA,NULL AS ID_CAPACITACION_RESULTADO,
    P.ID_CAPACITACION_PARTICIPANTE,E.ID_EMPLEADO,E.NUMERO_DOCUMENTO,
    CONCAT_WS(' ',E.NOMBRES,E.APELLIDOS) AS EMPLEADO,C.NOMBRE AS CAPACITACION,
    S.FECHA_FIN AS FECHA_REFERENCIA,NULL AS RESULTADO,0 AS REQUIERE_COMPROMISO,
    'La evaluacion de la capacitacion se encuentra pendiente.' AS MENSAJE,
    NULL AS ID_CAPACITACION_COMPROMISO
    FROM bbf_capacitacion_participantes P
    INNER JOIN bbf_empleados E ON E.ID_EMPLEADO=P.ID_EMPLEADO
    INNER JOIN bbf_capacitacion_sesiones S ON S.ID_CAPACITACION_SESION=P.ID_CAPACITACION_SESION
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    WHERE P.ESTADO_EVALUACION IN('PENDIENTE','EN_PROCESO') AND S.ESTADO<>'ANULADA'
      AND (P_ID_EMPLEADO IS NULL OR P_ID_EMPLEADO=0 OR E.ID_EMPLEADO=P_ID_EMPLEADO)

    UNION ALL

    SELECT 'RESULTADO_NO_APROBADO',R.ID_CAPACITACION_RESULTADO,
    P.ID_CAPACITACION_PARTICIPANTE,E.ID_EMPLEADO,E.NUMERO_DOCUMENTO,
    CONCAT_WS(' ',E.NOMBRES,E.APELLIDOS),C.NOMBRE,R.FECHA_RESULTADO,R.RESULTADO,
    R.REQUIERE_COMPROMISO,
    CONCAT('Resultado ',R.RESULTADO,'. Puntaje: ',COALESCE(R.PUNTAJE_FINAL,'sin definir'),'.'),
    CO.ID_CAPACITACION_COMPROMISO
    FROM bbf_capacitacion_resultados R
    INNER JOIN bbf_capacitacion_participantes P ON P.ID_CAPACITACION_PARTICIPANTE=R.ID_CAPACITACION_PARTICIPANTE
    INNER JOIN bbf_empleados E ON E.ID_EMPLEADO=P.ID_EMPLEADO
    INNER JOIN bbf_capacitacion_sesiones S ON S.ID_CAPACITACION_SESION=P.ID_CAPACITACION_SESION
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    LEFT JOIN bbf_capacitacion_compromisos CO ON CO.ID_CAPACITACION_RESULTADO=R.ID_CAPACITACION_RESULTADO
    WHERE R.RESULTADO IN('NO_APROBADO','REQUIERE_REINDUCCION')
      AND (P_ID_EMPLEADO IS NULL OR P_ID_EMPLEADO=0 OR E.ID_EMPLEADO=P_ID_EMPLEADO)
    ORDER BY FECHA_REFERENCIA DESC;
END$$
DELIMITER ;
