-- ============================================================================
-- BBF ADMINISTRATIVO - MODULO DE CAPACITACIONES
-- Base: bbf_administrativo | MariaDB 10.4+
-- Fecha: 2026-08-03
--
-- Modelo basado en la matriz semanal "Evaluacion y reinduccion de labores
-- cultivo". Cada valor diario se conserva por empleado, labor y fecha.
-- El acumulado semanal NO se interpreta automaticamente como nota final:
-- puntaje, minimo y resultado se almacenan por separado y son configurables.
--
-- Ejecutar primero en QA. El script es idempotente para catalogos y permisos;
-- los CREATE TABLE IF NOT EXISTS no modifican una instalacion parcial previa.
-- ============================================================================

USE `bbf_administrativo`;

-- ============================================================================
-- 0. VALIDACION PREVIA
-- ============================================================================

DELIMITER $$

DROP PROCEDURE IF EXISTS `SP_BBF_VALIDAR_MIGRACION_CAPACITACIONES`$$
CREATE PROCEDURE `SP_BBF_VALIDAR_MIGRACION_CAPACITACIONES`()
BEGIN
    IF DATABASE() <> 'bbf_administrativo' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Base incorrecta. Ejecute sobre bbf_administrativo.';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.TABLES
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'bbf_empleados'
    ) OR NOT EXISTS (
        SELECT 1 FROM information_schema.TABLES
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'bbf_usuarios'
    ) OR NOT EXISTS (
        SELECT 1 FROM information_schema.TABLES
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'bbf_permisos'
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Faltan tablas base requeridas: empleados, usuarios o permisos.';
    END IF;
END$$

CALL `SP_BBF_VALIDAR_MIGRACION_CAPACITACIONES`()$$
DROP PROCEDURE `SP_BBF_VALIDAR_MIGRACION_CAPACITACIONES`$$

DELIMITER ;

-- ============================================================================
-- 1. TABLAS
-- ============================================================================

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_labores` (
    `ID_CAPACITACION_LABOR` INT NOT NULL AUTO_INCREMENT,
    `CODIGO` VARCHAR(50) NOT NULL,
    `NOMBRE` VARCHAR(150) NOT NULL,
    `DESCRIPCION` VARCHAR(500) DEFAULT NULL,
    `ORDEN` INT NOT NULL DEFAULT 0,
    `ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_LABOR`),
    UNIQUE KEY `UQ_BBF_CAP_LABORES_CODIGO` (`CODIGO`),
    UNIQUE KEY `UQ_BBF_CAP_LABORES_NOMBRE` (`NOMBRE`),
    KEY `IDX_BBF_CAP_LABORES_ACTIVO_ORDEN` (`ACTIVO`, `ORDEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitaciones` (
    `ID_CAPACITACION` INT NOT NULL AUTO_INCREMENT,
    `CODIGO` VARCHAR(50) NOT NULL,
    `NOMBRE` VARCHAR(200) NOT NULL,
    `DESCRIPCION` TEXT DEFAULT NULL,
    `TIPO` ENUM('CAPACITACION','INDUCCION','REINDUCCION','EVALUACION_REINDUCCION') NOT NULL DEFAULT 'CAPACITACION',
    `REQUIERE_EVALUACION` TINYINT(1) NOT NULL DEFAULT 1,
    `REQUIERE_CONFIRMACION` TINYINT(1) NOT NULL DEFAULT 1,
    `PUNTAJE_MINIMO` DECIMAL(10,2) DEFAULT NULL,
    `PUNTAJE_MAXIMO` DECIMAL(10,2) DEFAULT NULL,
    `REGLA_CALCULO` VARCHAR(500) DEFAULT NULL,
    `GENERAR_COMPROMISO_NO_APROBADO` TINYINT(1) NOT NULL DEFAULT 0,
    `DIAS_PARA_EVALUAR` INT DEFAULT NULL,
    `ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
    `ID_CREADO_POR` INT NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION`),
    UNIQUE KEY `UQ_BBF_CAPACITACIONES_CODIGO` (`CODIGO`),
    KEY `IDX_BBF_CAPACITACIONES_TIPO_ACTIVO` (`TIPO`, `ACTIVO`),
    KEY `FK_BBF_CAPACITACIONES_CREADO_POR` (`ID_CREADO_POR`),
    CONSTRAINT `FK_BBF_CAPACITACIONES_CREADO_POR` FOREIGN KEY (`ID_CREADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `CK_BBF_CAPACITACIONES_PUNTAJES` CHECK (
        (`PUNTAJE_MINIMO` IS NULL OR `PUNTAJE_MINIMO` >= 0)
        AND (`PUNTAJE_MAXIMO` IS NULL OR `PUNTAJE_MAXIMO` > 0)
        AND (`PUNTAJE_MINIMO` IS NULL OR `PUNTAJE_MAXIMO` IS NULL OR `PUNTAJE_MINIMO` <= `PUNTAJE_MAXIMO`)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_labor_detalle` (
    `ID_CAPACITACION_LABOR_DETALLE` INT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION` INT NOT NULL,
    `ID_CAPACITACION_LABOR` INT NOT NULL,
    `PUNTAJE_MINIMO_LABOR` DECIMAL(10,2) DEFAULT NULL,
    `PUNTAJE_MAXIMO_LABOR` DECIMAL(10,2) DEFAULT NULL,
    `ORDEN` INT NOT NULL DEFAULT 0,
    `ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_LABOR_DETALLE`),
    UNIQUE KEY `UQ_BBF_CAP_LABOR_DETALLE` (`ID_CAPACITACION`, `ID_CAPACITACION_LABOR`),
    KEY `FK_BBF_CAP_LAB_DET_LABOR` (`ID_CAPACITACION_LABOR`),
    CONSTRAINT `FK_BBF_CAP_LAB_DET_CAP` FOREIGN KEY (`ID_CAPACITACION`) REFERENCES `bbf_capacitaciones` (`ID_CAPACITACION`),
    CONSTRAINT `FK_BBF_CAP_LAB_DET_LABOR` FOREIGN KEY (`ID_CAPACITACION_LABOR`) REFERENCES `bbf_capacitacion_labores` (`ID_CAPACITACION_LABOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_sesiones` (
    `ID_CAPACITACION_SESION` INT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION` INT NOT NULL,
    `CODIGO` VARCHAR(60) NOT NULL,
    `FECHA_INICIO` DATE NOT NULL,
    `FECHA_FIN` DATE NOT NULL,
    `ANIO_ISO` SMALLINT NOT NULL,
    `SEMANA_ISO` TINYINT NOT NULL,
    `ID_INSTRUCTOR_USUARIO` INT DEFAULT NULL,
    `INSTRUCTOR_EXTERNO` VARCHAR(200) DEFAULT NULL,
    `LUGAR` VARCHAR(250) DEFAULT NULL,
    `ESTADO` ENUM('BORRADOR','PROGRAMADA','EN_EJECUCION','CERRADA','ANULADA') NOT NULL DEFAULT 'BORRADOR',
    `OBSERVACIONES` TEXT DEFAULT NULL,
    `FECHA_CIERRE` DATETIME DEFAULT NULL,
    `ID_CREADO_POR` INT NOT NULL,
    `ID_CERRADO_POR` INT DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_SESION`),
    UNIQUE KEY `UQ_BBF_CAP_SESIONES_CODIGO` (`CODIGO`),
    UNIQUE KEY `UQ_BBF_CAP_SESION_PERIODO` (`ID_CAPACITACION`, `FECHA_INICIO`, `FECHA_FIN`),
    KEY `IDX_BBF_CAP_SESIONES_PERIODO` (`ANIO_ISO`, `SEMANA_ISO`, `ESTADO`),
    KEY `FK_BBF_CAP_SESIONES_INSTRUCTOR` (`ID_INSTRUCTOR_USUARIO`),
    KEY `FK_BBF_CAP_SESIONES_CREADO` (`ID_CREADO_POR`),
    KEY `FK_BBF_CAP_SESIONES_CERRADO` (`ID_CERRADO_POR`),
    CONSTRAINT `FK_BBF_CAP_SESIONES_CAP` FOREIGN KEY (`ID_CAPACITACION`) REFERENCES `bbf_capacitaciones` (`ID_CAPACITACION`),
    CONSTRAINT `FK_BBF_CAP_SESIONES_INSTRUCTOR` FOREIGN KEY (`ID_INSTRUCTOR_USUARIO`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `FK_BBF_CAP_SESIONES_CREADO` FOREIGN KEY (`ID_CREADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `FK_BBF_CAP_SESIONES_CERRADO` FOREIGN KEY (`ID_CERRADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `CK_BBF_CAP_SESIONES_FECHAS` CHECK (`FECHA_FIN` >= `FECHA_INICIO`),
    CONSTRAINT `CK_BBF_CAP_SESIONES_SEMANA` CHECK (`SEMANA_ISO` BETWEEN 1 AND 53)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_participantes` (
    `ID_CAPACITACION_PARTICIPANTE` INT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION_SESION` INT NOT NULL,
    `ID_EMPLEADO` INT NOT NULL,
    `ESTADO_ASISTENCIA` ENUM('PENDIENTE','ASISTIO','NO_ASISTIO','JUSTIFICADO','INCAPACITADO') NOT NULL DEFAULT 'PENDIENTE',
    `CONFIRMO_RECIBIDO` TINYINT(1) NOT NULL DEFAULT 0,
    `FECHA_CONFIRMACION` DATETIME DEFAULT NULL,
    `ID_CONFIRMADO_POR` INT DEFAULT NULL,
    `MODALIDAD_CONFIRMACION` ENUM('EMPLEADO','PRESENCIAL_RRHH') DEFAULT NULL,
    `OBSERVACION_CONFIRMACION` VARCHAR(500) DEFAULT NULL,
    `ESTADO_EVALUACION` ENUM('PENDIENTE','EN_PROCESO','EVALUADA','NO_APLICA') NOT NULL DEFAULT 'PENDIENTE',
    `OBSERVACIONES` TEXT DEFAULT NULL,
    `ID_REGISTRADO_POR` INT NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_PARTICIPANTE`),
    UNIQUE KEY `UQ_BBF_CAP_PARTICIPANTE` (`ID_CAPACITACION_SESION`, `ID_EMPLEADO`),
    KEY `IDX_BBF_CAP_PART_EMPLEADO` (`ID_EMPLEADO`, `ESTADO_EVALUACION`),
    KEY `FK_BBF_CAP_PART_CONFIRMADO` (`ID_CONFIRMADO_POR`),
    KEY `FK_BBF_CAP_PART_REGISTRADO` (`ID_REGISTRADO_POR`),
    CONSTRAINT `FK_BBF_CAP_PART_SESION` FOREIGN KEY (`ID_CAPACITACION_SESION`) REFERENCES `bbf_capacitacion_sesiones` (`ID_CAPACITACION_SESION`),
    CONSTRAINT `FK_BBF_CAP_PART_EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `bbf_empleados` (`ID_EMPLEADO`),
    CONSTRAINT `FK_BBF_CAP_PART_CONFIRMADO` FOREIGN KEY (`ID_CONFIRMADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `FK_BBF_CAP_PART_REGISTRADO` FOREIGN KEY (`ID_REGISTRADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_evaluaciones` (
    `ID_CAPACITACION_EVALUACION` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION_PARTICIPANTE` INT NOT NULL,
    `ID_CAPACITACION_LABOR` INT NOT NULL,
    `FECHA_EVALUACION` DATE NOT NULL,
    `VALOR_OBTENIDO` DECIMAL(12,2) NOT NULL,
    `VALOR_MAXIMO` DECIMAL(12,2) DEFAULT NULL,
    `REQUIERE_ATENCION` TINYINT(1) NOT NULL DEFAULT 0,
    `OBSERVACIONES` VARCHAR(500) DEFAULT NULL,
    `ID_EVALUADO_POR` INT NOT NULL,
    `ORIGEN` ENUM('MANUAL','EXCEL') NOT NULL DEFAULT 'MANUAL',
    `ID_CAPACITACION_IMPORTACION` BIGINT DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_EVALUACION`),
    UNIQUE KEY `UQ_BBF_CAP_EVAL_DIARIA` (`ID_CAPACITACION_PARTICIPANTE`, `ID_CAPACITACION_LABOR`, `FECHA_EVALUACION`),
    KEY `IDX_BBF_CAP_EVAL_FECHA` (`FECHA_EVALUACION`, `REQUIERE_ATENCION`),
    KEY `FK_BBF_CAP_EVAL_LABOR` (`ID_CAPACITACION_LABOR`),
    KEY `FK_BBF_CAP_EVAL_USUARIO` (`ID_EVALUADO_POR`),
    CONSTRAINT `FK_BBF_CAP_EVAL_PART` FOREIGN KEY (`ID_CAPACITACION_PARTICIPANTE`) REFERENCES `bbf_capacitacion_participantes` (`ID_CAPACITACION_PARTICIPANTE`),
    CONSTRAINT `FK_BBF_CAP_EVAL_LABOR` FOREIGN KEY (`ID_CAPACITACION_LABOR`) REFERENCES `bbf_capacitacion_labores` (`ID_CAPACITACION_LABOR`),
    CONSTRAINT `FK_BBF_CAP_EVAL_USUARIO` FOREIGN KEY (`ID_EVALUADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `CK_BBF_CAP_EVAL_VALORES` CHECK (`VALOR_OBTENIDO` >= 0 AND (`VALOR_MAXIMO` IS NULL OR `VALOR_MAXIMO` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_resultados` (
    `ID_CAPACITACION_RESULTADO` INT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION_PARTICIPANTE` INT NOT NULL,
    `FECHA_RESULTADO` DATE NOT NULL,
    `TOTAL_ACUMULADO` DECIMAL(14,2) DEFAULT NULL,
    `PUNTAJE_FINAL` DECIMAL(10,2) DEFAULT NULL,
    `PUNTAJE_MINIMO_APLICADO` DECIMAL(10,2) DEFAULT NULL,
    `RESULTADO` ENUM('PENDIENTE','APROBADO','NO_APROBADO','REQUIERE_REINDUCCION') NOT NULL DEFAULT 'PENDIENTE',
    `REQUIERE_REINDUCCION` TINYINT(1) NOT NULL DEFAULT 0,
    `REQUIERE_COMPROMISO` TINYINT(1) NOT NULL DEFAULT 0,
    `REGLA_APLICADA` VARCHAR(500) DEFAULT NULL,
    `OBSERVACIONES` TEXT DEFAULT NULL,
    `ID_REGISTRADO_POR` INT NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_RESULTADO`),
    UNIQUE KEY `UQ_BBF_CAP_RESULTADO_PART` (`ID_CAPACITACION_PARTICIPANTE`),
    KEY `IDX_BBF_CAP_RESULTADO_ALERTA` (`RESULTADO`, `REQUIERE_COMPROMISO`),
    KEY `FK_BBF_CAP_RESULTADO_USUARIO` (`ID_REGISTRADO_POR`),
    CONSTRAINT `FK_BBF_CAP_RESULTADO_PART` FOREIGN KEY (`ID_CAPACITACION_PARTICIPANTE`) REFERENCES `bbf_capacitacion_participantes` (`ID_CAPACITACION_PARTICIPANTE`),
    CONSTRAINT `FK_BBF_CAP_RESULTADO_USUARIO` FOREIGN KEY (`ID_REGISTRADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_compromisos` (
    `ID_CAPACITACION_COMPROMISO` INT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION_RESULTADO` INT NOT NULL,
    `FECHA_COMPROMISO` DATE NOT NULL,
    `FECHA_LIMITE` DATE DEFAULT NULL,
    `MOTIVO` TEXT NOT NULL,
    `COMPROMISOS_EMPLEADO` TEXT DEFAULT NULL,
    `ESTADO` ENUM('BORRADOR','PENDIENTE_FIRMA','FIRMADO','CUMPLIDO','INCUMPLIDO','ANULADO') NOT NULL DEFAULT 'BORRADOR',
    `DOCUMENTO_URL` VARCHAR(500) DEFAULT NULL,
    `DOCUMENTO_RUTA` VARCHAR(500) DEFAULT NULL,
    `FIRMA_URL` VARCHAR(500) DEFAULT NULL,
    `FECHA_FIRMA` DATETIME DEFAULT NULL,
    `OBSERVACIONES` TEXT DEFAULT NULL,
    `ID_CREADO_POR` INT NOT NULL,
    `ID_CERRADO_POR` INT DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_COMPROMISO`),
    UNIQUE KEY `UQ_BBF_CAP_COMPROMISO_RESULTADO` (`ID_CAPACITACION_RESULTADO`),
    KEY `IDX_BBF_CAP_COMPROMISO_ESTADO` (`ESTADO`, `FECHA_LIMITE`),
    KEY `FK_BBF_CAP_COMPROMISO_CREADO` (`ID_CREADO_POR`),
    KEY `FK_BBF_CAP_COMPROMISO_CERRADO` (`ID_CERRADO_POR`),
    CONSTRAINT `FK_BBF_CAP_COMPROMISO_RESULTADO` FOREIGN KEY (`ID_CAPACITACION_RESULTADO`) REFERENCES `bbf_capacitacion_resultados` (`ID_CAPACITACION_RESULTADO`),
    CONSTRAINT `FK_BBF_CAP_COMPROMISO_CREADO` FOREIGN KEY (`ID_CREADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `FK_BBF_CAP_COMPROMISO_CERRADO` FOREIGN KEY (`ID_CERRADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_importaciones` (
    `ID_CAPACITACION_IMPORTACION` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION_SESION` INT DEFAULT NULL,
    `NOMBRE_ARCHIVO` VARCHAR(255) NOT NULL,
    `NOMBRE_ORIGINAL` VARCHAR(255) NOT NULL,
    `ARCHIVO_RUTA` VARCHAR(500) NOT NULL,
    `MIME_TYPE` VARCHAR(100) DEFAULT NULL,
    `PESO_BYTES` BIGINT DEFAULT NULL,
    `ESTADO` ENUM('CARGADA','VALIDANDO','CON_ERRORES','VALIDADA','IMPORTADA','ANULADA') NOT NULL DEFAULT 'CARGADA',
    `TOTAL_REGISTROS` INT NOT NULL DEFAULT 0,
    `TOTAL_VALIDOS` INT NOT NULL DEFAULT 0,
    `TOTAL_ERRORES` INT NOT NULL DEFAULT 0,
    `RESUMEN` TEXT DEFAULT NULL,
    `ID_CARGADO_POR` INT NOT NULL,
    `FECHA_IMPORTACION` DATETIME DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_IMPORTACION`),
    KEY `IDX_BBF_CAP_IMPORT_ESTADO` (`ESTADO`, `CREATED_AT`),
    KEY `FK_BBF_CAP_IMPORT_SESION` (`ID_CAPACITACION_SESION`),
    KEY `FK_BBF_CAP_IMPORT_USUARIO` (`ID_CARGADO_POR`),
    CONSTRAINT `FK_BBF_CAP_IMPORT_SESION` FOREIGN KEY (`ID_CAPACITACION_SESION`) REFERENCES `bbf_capacitacion_sesiones` (`ID_CAPACITACION_SESION`),
    CONSTRAINT `FK_BBF_CAP_IMPORT_USUARIO` FOREIGN KEY (`ID_CARGADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_importacion_errores` (
    `ID_CAPACITACION_IMPORTACION_ERROR` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION_IMPORTACION` BIGINT NOT NULL,
    `HOJA` VARCHAR(150) DEFAULT NULL,
    `CELDA` VARCHAR(30) DEFAULT NULL,
    `FILA` INT DEFAULT NULL,
    `EMPLEADO_ORIGINAL` VARCHAR(250) DEFAULT NULL,
    `LABOR_ORIGINAL` VARCHAR(250) DEFAULT NULL,
    `VALOR_ORIGINAL` VARCHAR(500) DEFAULT NULL,
    `CODIGO_ERROR` VARCHAR(80) NOT NULL,
    `MENSAJE` VARCHAR(500) NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_IMPORTACION_ERROR`),
    KEY `IDX_BBF_CAP_IMPORT_ERROR_IMPORT` (`ID_CAPACITACION_IMPORTACION`, `FILA`),
    CONSTRAINT `FK_BBF_CAP_IMPORT_ERROR_IMPORT` FOREIGN KEY (`ID_CAPACITACION_IMPORTACION`) REFERENCES `bbf_capacitacion_importaciones` (`ID_CAPACITACION_IMPORTACION`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bbf_capacitacion_evidencias` (
    `ID_CAPACITACION_EVIDENCIA` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_CAPACITACION_SESION` INT DEFAULT NULL,
    `ID_CAPACITACION_PARTICIPANTE` INT DEFAULT NULL,
    `ID_CAPACITACION_COMPROMISO` INT DEFAULT NULL,
    `TIPO_EVIDENCIA` ENUM('ASISTENCIA','CONFIRMACION','EVALUACION','FIRMA','COMPROMISO','OTRA') NOT NULL,
    `NOMBRE_ARCHIVO` VARCHAR(255) NOT NULL,
    `NOMBRE_ORIGINAL` VARCHAR(255) DEFAULT NULL,
    `ARCHIVO_URL` VARCHAR(500) DEFAULT NULL,
    `ARCHIVO_RUTA` VARCHAR(500) DEFAULT NULL,
    `MIME_TYPE` VARCHAR(100) DEFAULT NULL,
    `PESO_BYTES` BIGINT DEFAULT NULL,
    `ID_CARGADO_POR` INT NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_CAPACITACION_EVIDENCIA`),
    KEY `IDX_BBF_CAP_EVID_SESION` (`ID_CAPACITACION_SESION`),
    KEY `IDX_BBF_CAP_EVID_PART` (`ID_CAPACITACION_PARTICIPANTE`),
    KEY `IDX_BBF_CAP_EVID_COMP` (`ID_CAPACITACION_COMPROMISO`),
    KEY `FK_BBF_CAP_EVID_USUARIO` (`ID_CARGADO_POR`),
    CONSTRAINT `FK_BBF_CAP_EVID_SESION` FOREIGN KEY (`ID_CAPACITACION_SESION`) REFERENCES `bbf_capacitacion_sesiones` (`ID_CAPACITACION_SESION`),
    CONSTRAINT `FK_BBF_CAP_EVID_PART` FOREIGN KEY (`ID_CAPACITACION_PARTICIPANTE`) REFERENCES `bbf_capacitacion_participantes` (`ID_CAPACITACION_PARTICIPANTE`),
    CONSTRAINT `FK_BBF_CAP_EVID_COMP` FOREIGN KEY (`ID_CAPACITACION_COMPROMISO`) REFERENCES `bbf_capacitacion_compromisos` (`ID_CAPACITACION_COMPROMISO`),
    CONSTRAINT `FK_BBF_CAP_EVID_USUARIO` FOREIGN KEY (`ID_CARGADO_POR`) REFERENCES `bbf_usuarios` (`ID_USUARIO`),
    CONSTRAINT `CK_BBF_CAP_EVID_ORIGEN` CHECK (`ARCHIVO_URL` IS NOT NULL OR `ARCHIVO_RUTA` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- FK diferida porque importaciones se crea despues de evaluaciones.
SET @FK_IMPORT_EVAL_EXISTE := (
    SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_SCHEMA = DATABASE()
      AND TABLE_NAME = 'bbf_capacitacion_evaluaciones'
      AND CONSTRAINT_NAME = 'FK_BBF_CAP_EVAL_IMPORT'
);
SET @SQL_FK_IMPORT_EVAL := IF(
    @FK_IMPORT_EVAL_EXISTE = 0,
    'ALTER TABLE bbf_capacitacion_evaluaciones ADD KEY IDX_BBF_CAP_EVAL_IMPORT (ID_CAPACITACION_IMPORTACION), ADD CONSTRAINT FK_BBF_CAP_EVAL_IMPORT FOREIGN KEY (ID_CAPACITACION_IMPORTACION) REFERENCES bbf_capacitacion_importaciones (ID_CAPACITACION_IMPORTACION)',
    'SELECT 1'
);
PREPARE STMT_FK_IMPORT_EVAL FROM @SQL_FK_IMPORT_EVAL;
EXECUTE STMT_FK_IMPORT_EVAL;
DEALLOCATE PREPARE STMT_FK_IMPORT_EVAL;

-- ============================================================================
-- 2. CATALOGOS INICIALES
-- ============================================================================

INSERT INTO `bbf_capacitacion_labores` (`CODIGO`,`NOMBRE`,`ORDEN`,`ACTIVO`) VALUES
('DESBOTONE','Desbotone',1,1),
('PINCH','Pinch',2,1),
('GUIADA_TALLOS','Guiada de tallos',3,1),
('PROGRAMACIONES','Programaciones',4,1),
('DESHIERBE','Deshierbe',5,1),
('DESCHUPONADO','Deschuponado',6,1),
('BARRIDA','Barrida',7,1),
('PALO_SECO','Palo seco',8,1),
('ENMALLE','Enmalle',9,1),
('SELECCION_BROTES','Seleccion de brotes',10,1),
('ENTRESAQUE','Entresaque',11,1),
('REPORTES_FITOSANITARIOS','Reportes fitosanitarios',12,1)
ON DUPLICATE KEY UPDATE `NOMBRE`=VALUES(`NOMBRE`),`ORDEN`=VALUES(`ORDEN`),`ACTIVO`=1;

INSERT INTO `bbf_capacitaciones`
(`CODIGO`,`NOMBRE`,`DESCRIPCION`,`TIPO`,`REQUIERE_EVALUACION`,`REQUIERE_CONFIRMACION`,`PUNTAJE_MINIMO`,`PUNTAJE_MAXIMO`,`REGLA_CALCULO`,`GENERAR_COMPROMISO_NO_APROBADO`,`ID_CREADO_POR`)
SELECT
    'EVAL_REIND_CULTIVO',
    'Evaluacion y reinduccion de labores de cultivo',
    'Registro semanal por empleado, labor y dia basado en la matriz actual del cliente.',
    'EVALUACION_REINDUCCION',1,1,NULL,NULL,
    'Pendiente de validacion con el cliente. El acumulado y el puntaje final se registran por separado.',
    0,
    U.ID_USUARIO
FROM bbf_usuarios U
WHERE U.ESTADO='ACTIVO'
ORDER BY CASE WHEN U.TIPO_USUARIO='ADMIN' THEN 0 ELSE 1 END,U.ID_USUARIO
LIMIT 1
ON DUPLICATE KEY UPDATE `NOMBRE`=VALUES(`NOMBRE`),`DESCRIPCION`=VALUES(`DESCRIPCION`),`ACTIVO`=1;

INSERT INTO `bbf_capacitacion_labor_detalle`
(`ID_CAPACITACION`,`ID_CAPACITACION_LABOR`,`ORDEN`,`ACTIVO`)
SELECT C.ID_CAPACITACION,L.ID_CAPACITACION_LABOR,L.ORDEN,1
FROM bbf_capacitaciones C
CROSS JOIN bbf_capacitacion_labores L
WHERE C.CODIGO='EVAL_REIND_CULTIVO'
ON DUPLICATE KEY UPDATE `ORDEN`=VALUES(`ORDEN`),`ACTIVO`=1;

-- ============================================================================
-- 3. PERMISOS
-- ============================================================================

INSERT INTO `bbf_permisos` (`CODIGO`,`NOMBRE`,`DESCRIPCION`,`MODULO`,`ACTIVO`) VALUES
('CAPACITACIONES_VER','Ver capacitaciones','Permite consultar catalogos, sesiones, participantes y resultados.','CAPACITACIONES',1),
('CAPACITACIONES_ADMINISTRAR','Administrar capacitaciones','Permite crear catalogos, sesiones y asociar participantes.','CAPACITACIONES',1),
('CAPACITACIONES_EVALUAR','Evaluar capacitaciones','Permite registrar evaluaciones y resultados.','CAPACITACIONES',1),
('CAPACITACIONES_IMPORTAR','Importar evaluaciones','Permite cargar e importar archivos Excel de evaluacion.','CAPACITACIONES',1),
('CAPACITACIONES_COMPROMISOS','Gestionar compromisos','Permite generar y actualizar cartas de compromiso.','CAPACITACIONES',1),
('CAPACITACIONES_MIS_REGISTROS_VER','Ver mis capacitaciones','Permite al empleado consultar sus capacitaciones y resultados.','CAPACITACIONES',1),
('CAPACITACIONES_CONFIRMAR','Confirmar capacitacion recibida','Permite al empleado confirmar que recibio una capacitacion.','CAPACITACIONES',1)
ON DUPLICATE KEY UPDATE `NOMBRE`=VALUES(`NOMBRE`),`DESCRIPCION`=VALUES(`DESCRIPCION`),`MODULO`=VALUES(`MODULO`),`ACTIVO`=1;

-- SUPER_ADMIN recibe todos los permisos del modulo.
INSERT INTO `bbf_rol_permisos` (`ID_ROL`,`ID_PERMISO`)
SELECT R.ID_ROL,P.ID_PERMISO
FROM bbf_roles R
CROSS JOIN bbf_permisos P
WHERE R.NOMBRE='SUPER_ADMIN'
  AND R.ACTIVO=1 AND R.ELIMINADO=0
  AND P.CODIGO LIKE 'CAPACITACIONES_%'
ON DUPLICATE KEY UPDATE `ID_PERMISO`=VALUES(`ID_PERMISO`);

-- Empleados reciben solo consulta propia y confirmacion.
INSERT INTO `bbf_rol_permisos` (`ID_ROL`,`ID_PERMISO`)
SELECT R.ID_ROL,P.ID_PERMISO
FROM bbf_roles R
CROSS JOIN bbf_permisos P
WHERE R.NOMBRE='EMPLEADO_ROL'
  AND R.ACTIVO=1 AND R.ELIMINADO=0
  AND P.CODIGO IN ('CAPACITACIONES_MIS_REGISTROS_VER','CAPACITACIONES_CONFIRMAR')
ON DUPLICATE KEY UPDATE `ID_PERMISO`=VALUES(`ID_PERMISO`);

-- ============================================================================
-- 4. PROCEDIMIENTOS ALMACENADOS
-- ============================================================================

DELIMITER $$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_LABORES_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_LABORES_LISTAR`(IN P_INCLUIR_INACTIVAS TINYINT)
BEGIN
    SELECT ID_CAPACITACION_LABOR,CODIGO,NOMBRE,DESCRIPCION,ORDEN,ACTIVO,CREATED_AT,UPDATED_AT
    FROM bbf_capacitacion_labores
    WHERE IFNULL(P_INCLUIR_INACTIVAS,0)=1 OR ACTIVO=1
    ORDER BY ORDEN,NOMBRE;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_LABOR_GUARDAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_LABOR_GUARDAR`(
    IN P_ID_CAPACITACION_LABOR INT, IN P_CODIGO VARCHAR(50), IN P_NOMBRE VARCHAR(150),
    IN P_DESCRIPCION VARCHAR(500), IN P_ORDEN INT, IN P_ACTIVO TINYINT
)
BEGIN
    IF NULLIF(TRIM(P_CODIGO),'') IS NULL OR NULLIF(TRIM(P_NOMBRE),'') IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Codigo y nombre de la labor son obligatorios.';
    END IF;
    IF P_ID_CAPACITACION_LABOR IS NULL OR P_ID_CAPACITACION_LABOR=0 THEN
        INSERT INTO bbf_capacitacion_labores(CODIGO,NOMBRE,DESCRIPCION,ORDEN,ACTIVO)
        VALUES(UPPER(TRIM(P_CODIGO)),TRIM(P_NOMBRE),NULLIF(TRIM(P_DESCRIPCION),''),IFNULL(P_ORDEN,0),IFNULL(P_ACTIVO,1));
        SET P_ID_CAPACITACION_LABOR=LAST_INSERT_ID();
    ELSE
        UPDATE bbf_capacitacion_labores SET CODIGO=UPPER(TRIM(P_CODIGO)),NOMBRE=TRIM(P_NOMBRE),
        DESCRIPCION=NULLIF(TRIM(P_DESCRIPCION),''),ORDEN=IFNULL(P_ORDEN,0),ACTIVO=IFNULL(P_ACTIVO,1)
        WHERE ID_CAPACITACION_LABOR=P_ID_CAPACITACION_LABOR;
    END IF;
    SELECT * FROM bbf_capacitacion_labores WHERE ID_CAPACITACION_LABOR=P_ID_CAPACITACION_LABOR;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACIONES_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACIONES_LISTAR`(IN P_TIPO VARCHAR(30), IN P_INCLUIR_INACTIVAS TINYINT)
BEGIN
    SELECT C.*,COUNT(CASE WHEN D.ACTIVO=1 THEN 1 END) AS TOTAL_LABORES
    FROM bbf_capacitaciones C
    LEFT JOIN bbf_capacitacion_labor_detalle D ON D.ID_CAPACITACION=C.ID_CAPACITACION
    WHERE (NULLIF(TRIM(P_TIPO),'') IS NULL OR C.TIPO=UPPER(TRIM(P_TIPO)))
      AND (IFNULL(P_INCLUIR_INACTIVAS,0)=1 OR C.ACTIVO=1)
    GROUP BY C.ID_CAPACITACION
    ORDER BY C.ACTIVO DESC,C.NOMBRE;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_GUARDAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_GUARDAR`(
    IN P_ID_CAPACITACION INT, IN P_CODIGO VARCHAR(50), IN P_NOMBRE VARCHAR(200),
    IN P_DESCRIPCION TEXT, IN P_TIPO VARCHAR(30), IN P_REQUIERE_EVALUACION TINYINT,
    IN P_REQUIERE_CONFIRMACION TINYINT, IN P_PUNTAJE_MINIMO DECIMAL(10,2),
    IN P_PUNTAJE_MAXIMO DECIMAL(10,2), IN P_REGLA_CALCULO VARCHAR(500),
    IN P_GENERAR_COMPROMISO TINYINT, IN P_DIAS_PARA_EVALUAR INT,
    IN P_ACTIVO TINYINT, IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_TIPO VARCHAR(30);
    SET V_TIPO=UPPER(TRIM(P_TIPO));
    IF V_TIPO NOT IN('CAPACITACION','INDUCCION','REINDUCCION','EVALUACION_REINDUCCION') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tipo de capacitacion no valido.';
    END IF;
    IF P_PUNTAJE_MINIMO IS NOT NULL AND P_PUNTAJE_MAXIMO IS NOT NULL AND P_PUNTAJE_MINIMO>P_PUNTAJE_MAXIMO THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El puntaje minimo no puede superar el maximo.';
    END IF;
    IF P_ID_CAPACITACION IS NULL OR P_ID_CAPACITACION=0 THEN
        INSERT INTO bbf_capacitaciones(CODIGO,NOMBRE,DESCRIPCION,TIPO,REQUIERE_EVALUACION,REQUIERE_CONFIRMACION,
        PUNTAJE_MINIMO,PUNTAJE_MAXIMO,REGLA_CALCULO,GENERAR_COMPROMISO_NO_APROBADO,DIAS_PARA_EVALUAR,ACTIVO,ID_CREADO_POR)
        VALUES(UPPER(TRIM(P_CODIGO)),TRIM(P_NOMBRE),NULLIF(TRIM(P_DESCRIPCION),''),V_TIPO,
        IFNULL(P_REQUIERE_EVALUACION,1),IFNULL(P_REQUIERE_CONFIRMACION,1),P_PUNTAJE_MINIMO,P_PUNTAJE_MAXIMO,
        NULLIF(TRIM(P_REGLA_CALCULO),''),IFNULL(P_GENERAR_COMPROMISO,0),P_DIAS_PARA_EVALUAR,IFNULL(P_ACTIVO,1),P_ID_USUARIO);
        SET P_ID_CAPACITACION=LAST_INSERT_ID();
    ELSE
        UPDATE bbf_capacitaciones SET CODIGO=UPPER(TRIM(P_CODIGO)),NOMBRE=TRIM(P_NOMBRE),
        DESCRIPCION=NULLIF(TRIM(P_DESCRIPCION),''),TIPO=V_TIPO,REQUIERE_EVALUACION=IFNULL(P_REQUIERE_EVALUACION,1),
        REQUIERE_CONFIRMACION=IFNULL(P_REQUIERE_CONFIRMACION,1),PUNTAJE_MINIMO=P_PUNTAJE_MINIMO,
        PUNTAJE_MAXIMO=P_PUNTAJE_MAXIMO,REGLA_CALCULO=NULLIF(TRIM(P_REGLA_CALCULO),''),
        GENERAR_COMPROMISO_NO_APROBADO=IFNULL(P_GENERAR_COMPROMISO,0),DIAS_PARA_EVALUAR=P_DIAS_PARA_EVALUAR,
        ACTIVO=IFNULL(P_ACTIVO,1) WHERE ID_CAPACITACION=P_ID_CAPACITACION;
    END IF;
    SELECT * FROM bbf_capacitaciones WHERE ID_CAPACITACION=P_ID_CAPACITACION;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_LABOR_ASOCIAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_LABOR_ASOCIAR`(
    IN P_ID_CAPACITACION INT, IN P_ID_CAPACITACION_LABOR INT,
    IN P_PUNTAJE_MINIMO DECIMAL(10,2), IN P_PUNTAJE_MAXIMO DECIMAL(10,2), IN P_ORDEN INT
)
BEGIN
    IF NOT EXISTS(SELECT 1 FROM bbf_capacitaciones WHERE ID_CAPACITACION=P_ID_CAPACITACION AND ACTIVO=1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La capacitacion no existe o esta inactiva.';
    END IF;
    IF NOT EXISTS(SELECT 1 FROM bbf_capacitacion_labores WHERE ID_CAPACITACION_LABOR=P_ID_CAPACITACION_LABOR AND ACTIVO=1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La labor no existe o esta inactiva.';
    END IF;
    INSERT INTO bbf_capacitacion_labor_detalle(ID_CAPACITACION,ID_CAPACITACION_LABOR,PUNTAJE_MINIMO_LABOR,PUNTAJE_MAXIMO_LABOR,ORDEN,ACTIVO)
    VALUES(P_ID_CAPACITACION,P_ID_CAPACITACION_LABOR,P_PUNTAJE_MINIMO,P_PUNTAJE_MAXIMO,IFNULL(P_ORDEN,0),1)
    ON DUPLICATE KEY UPDATE PUNTAJE_MINIMO_LABOR=VALUES(PUNTAJE_MINIMO_LABOR),PUNTAJE_MAXIMO_LABOR=VALUES(PUNTAJE_MAXIMO_LABOR),ORDEN=VALUES(ORDEN),ACTIVO=1;
    SELECT * FROM bbf_capacitacion_labor_detalle WHERE ID_CAPACITACION=P_ID_CAPACITACION AND ID_CAPACITACION_LABOR=P_ID_CAPACITACION_LABOR;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_SESION_CREAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_SESION_CREAR`(
    IN P_ID_CAPACITACION INT, IN P_FECHA_INICIO DATE, IN P_FECHA_FIN DATE,
    IN P_ID_INSTRUCTOR_USUARIO INT, IN P_INSTRUCTOR_EXTERNO VARCHAR(200),
    IN P_LUGAR VARCHAR(250), IN P_OBSERVACIONES TEXT, IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_CODIGO VARCHAR(60);
    IF P_FECHA_INICIO IS NULL OR P_FECHA_FIN IS NULL OR P_FECHA_FIN<P_FECHA_INICIO THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El rango de fechas de la sesion no es valido.';
    END IF;
    IF NOT EXISTS(SELECT 1 FROM bbf_capacitaciones WHERE ID_CAPACITACION=P_ID_CAPACITACION AND ACTIVO=1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La capacitacion no existe o esta inactiva.';
    END IF;
    SET V_CODIGO=CONCAT('CAP-',P_ID_CAPACITACION,'-',YEARWEEK(P_FECHA_INICIO,3),'-',DATE_FORMAT(P_FECHA_INICIO,'%m%d'));
    INSERT INTO bbf_capacitacion_sesiones(ID_CAPACITACION,CODIGO,FECHA_INICIO,FECHA_FIN,ANIO_ISO,SEMANA_ISO,
    ID_INSTRUCTOR_USUARIO,INSTRUCTOR_EXTERNO,LUGAR,ESTADO,OBSERVACIONES,ID_CREADO_POR)
    VALUES(P_ID_CAPACITACION,V_CODIGO,P_FECHA_INICIO,P_FECHA_FIN,
    YEAR(DATE_ADD(DATE_SUB(P_FECHA_INICIO,INTERVAL WEEKDAY(P_FECHA_INICIO) DAY),INTERVAL 3 DAY)),
    WEEK(P_FECHA_INICIO,3),P_ID_INSTRUCTOR_USUARIO,NULLIF(TRIM(P_INSTRUCTOR_EXTERNO),''),NULLIF(TRIM(P_LUGAR),''),'BORRADOR',
    NULLIF(TRIM(P_OBSERVACIONES),''),P_ID_USUARIO);
    SELECT * FROM bbf_capacitacion_sesiones WHERE ID_CAPACITACION_SESION=LAST_INSERT_ID();
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_SESIONES_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_SESIONES_LISTAR`(
    IN P_ID_CAPACITACION INT, IN P_ANIO SMALLINT, IN P_SEMANA TINYINT, IN P_ESTADO VARCHAR(20)
)
BEGIN
    SELECT S.*,C.CODIGO AS CODIGO_CAPACITACION,C.NOMBRE AS CAPACITACION,C.TIPO,
    COUNT(DISTINCT P.ID_CAPACITACION_PARTICIPANTE) AS TOTAL_PARTICIPANTES,
    SUM(CASE WHEN P.ESTADO_EVALUACION='PENDIENTE' THEN 1 ELSE 0 END) AS EVALUACIONES_PENDIENTES
    FROM bbf_capacitacion_sesiones S
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    LEFT JOIN bbf_capacitacion_participantes P ON P.ID_CAPACITACION_SESION=S.ID_CAPACITACION_SESION
    WHERE (P_ID_CAPACITACION IS NULL OR P_ID_CAPACITACION=0 OR S.ID_CAPACITACION=P_ID_CAPACITACION)
      AND (P_ANIO IS NULL OR P_ANIO=0 OR S.ANIO_ISO=P_ANIO)
      AND (P_SEMANA IS NULL OR P_SEMANA=0 OR S.SEMANA_ISO=P_SEMANA)
      AND (NULLIF(TRIM(P_ESTADO),'') IS NULL OR S.ESTADO=UPPER(TRIM(P_ESTADO)))
    GROUP BY S.ID_CAPACITACION_SESION
    ORDER BY S.FECHA_INICIO DESC,S.ID_CAPACITACION_SESION DESC;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_SESION_CAMBIAR_ESTADO`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_SESION_CAMBIAR_ESTADO`(
    IN P_ID_SESION INT, IN P_ESTADO VARCHAR(20), IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_ESTADO VARCHAR(20);
    SET V_ESTADO=UPPER(TRIM(P_ESTADO));
    IF V_ESTADO NOT IN('BORRADOR','PROGRAMADA','EN_EJECUCION','CERRADA','ANULADA') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Estado de sesion no valido.';
    END IF;
    IF V_ESTADO='CERRADA' AND EXISTS(
        SELECT 1 FROM bbf_capacitacion_participantes WHERE ID_CAPACITACION_SESION=P_ID_SESION AND ESTADO_EVALUACION IN('PENDIENTE','EN_PROCESO')
    ) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='No se puede cerrar: existen evaluaciones pendientes.';
    END IF;
    UPDATE bbf_capacitacion_sesiones SET ESTADO=V_ESTADO,
    FECHA_CIERRE=CASE WHEN V_ESTADO='CERRADA' THEN CURRENT_TIMESTAMP ELSE FECHA_CIERRE END,
    ID_CERRADO_POR=CASE WHEN V_ESTADO='CERRADA' THEN P_ID_USUARIO ELSE ID_CERRADO_POR END
    WHERE ID_CAPACITACION_SESION=P_ID_SESION;
    SELECT * FROM bbf_capacitacion_sesiones WHERE ID_CAPACITACION_SESION=P_ID_SESION;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_PARTICIPANTE_AGREGAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_PARTICIPANTE_AGREGAR`(
    IN P_ID_SESION INT, IN P_ID_EMPLEADO INT, IN P_OBSERVACIONES TEXT, IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_REQUIERE_EVALUACION TINYINT;
    IF NOT EXISTS(SELECT 1 FROM bbf_empleados WHERE ID_EMPLEADO=P_ID_EMPLEADO AND ELIMINADO=0) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El empleado no existe o fue eliminado.';
    END IF;
    SELECT C.REQUIERE_EVALUACION INTO V_REQUIERE_EVALUACION
    FROM bbf_capacitacion_sesiones S INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    WHERE S.ID_CAPACITACION_SESION=P_ID_SESION AND S.ESTADO<>'ANULADA' LIMIT 1;
    IF V_REQUIERE_EVALUACION IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La sesion no existe o esta anulada.'; END IF;
    INSERT INTO bbf_capacitacion_participantes(ID_CAPACITACION_SESION,ID_EMPLEADO,ESTADO_EVALUACION,OBSERVACIONES,ID_REGISTRADO_POR)
    VALUES(P_ID_SESION,P_ID_EMPLEADO,IF(V_REQUIERE_EVALUACION=1,'PENDIENTE','NO_APLICA'),NULLIF(TRIM(P_OBSERVACIONES),''),P_ID_USUARIO)
    ON DUPLICATE KEY UPDATE OBSERVACIONES=VALUES(OBSERVACIONES);
    SELECT * FROM bbf_capacitacion_participantes WHERE ID_CAPACITACION_SESION=P_ID_SESION AND ID_EMPLEADO=P_ID_EMPLEADO;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_ASISTENCIA_REGISTRAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_ASISTENCIA_REGISTRAR`(
    IN P_ID_PARTICIPANTE INT, IN P_ESTADO VARCHAR(20), IN P_OBSERVACIONES TEXT
)
BEGIN
    DECLARE V_ESTADO VARCHAR(20);
    SET V_ESTADO=UPPER(TRIM(P_ESTADO));
    IF V_ESTADO NOT IN('PENDIENTE','ASISTIO','NO_ASISTIO','JUSTIFICADO','INCAPACITADO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Estado de asistencia no valido.';
    END IF;
    UPDATE bbf_capacitacion_participantes SET ESTADO_ASISTENCIA=V_ESTADO,
    ESTADO_EVALUACION=CASE
        WHEN V_ESTADO IN('NO_ASISTIO','JUSTIFICADO','INCAPACITADO') THEN 'NO_APLICA'
        WHEN V_ESTADO='ASISTIO' AND ESTADO_EVALUACION='NO_APLICA' THEN 'PENDIENTE'
        ELSE ESTADO_EVALUACION
    END,
    OBSERVACIONES=COALESCE(NULLIF(TRIM(P_OBSERVACIONES),''),OBSERVACIONES)
    WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE;
    SELECT * FROM bbf_capacitacion_participantes WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_EVALUACION_GUARDAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_EVALUACION_GUARDAR`(
    IN P_ID_PARTICIPANTE INT, IN P_ID_LABOR INT, IN P_FECHA DATE,
    IN P_VALOR DECIMAL(12,2), IN P_VALOR_MAXIMO DECIMAL(12,2), IN P_REQUIERE_ATENCION TINYINT,
    IN P_OBSERVACIONES VARCHAR(500), IN P_ID_EVALUADOR INT, IN P_ORIGEN VARCHAR(10), IN P_ID_IMPORTACION BIGINT
)
BEGIN
    DECLARE V_INICIO DATE; DECLARE V_FIN DATE; DECLARE V_ID_CAPACITACION INT;
    SELECT S.FECHA_INICIO,S.FECHA_FIN,S.ID_CAPACITACION INTO V_INICIO,V_FIN,V_ID_CAPACITACION
    FROM bbf_capacitacion_participantes P INNER JOIN bbf_capacitacion_sesiones S ON S.ID_CAPACITACION_SESION=P.ID_CAPACITACION_SESION
    WHERE P.ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE LIMIT 1;
    IF V_INICIO IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El participante no existe.'; END IF;
    IF P_FECHA<V_INICIO OR P_FECHA>V_FIN THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La fecha no pertenece al periodo de la sesion.'; END IF;
    IF P_VALOR IS NULL OR P_VALOR<0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El valor obtenido debe ser mayor o igual a cero.'; END IF;
    IF NOT EXISTS(SELECT 1 FROM bbf_capacitacion_labor_detalle WHERE ID_CAPACITACION=V_ID_CAPACITACION AND ID_CAPACITACION_LABOR=P_ID_LABOR AND ACTIVO=1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='La labor no pertenece a la capacitacion.';
    END IF;
    INSERT INTO bbf_capacitacion_evaluaciones(ID_CAPACITACION_PARTICIPANTE,ID_CAPACITACION_LABOR,FECHA_EVALUACION,
    VALOR_OBTENIDO,VALOR_MAXIMO,REQUIERE_ATENCION,OBSERVACIONES,ID_EVALUADO_POR,ORIGEN,ID_CAPACITACION_IMPORTACION)
    VALUES(P_ID_PARTICIPANTE,P_ID_LABOR,P_FECHA,P_VALOR,P_VALOR_MAXIMO,IFNULL(P_REQUIERE_ATENCION,0),
    NULLIF(TRIM(P_OBSERVACIONES),''),P_ID_EVALUADOR,IF(UPPER(P_ORIGEN)='EXCEL','EXCEL','MANUAL'),P_ID_IMPORTACION)
    ON DUPLICATE KEY UPDATE VALOR_OBTENIDO=VALUES(VALOR_OBTENIDO),VALOR_MAXIMO=VALUES(VALOR_MAXIMO),
    REQUIERE_ATENCION=VALUES(REQUIERE_ATENCION),OBSERVACIONES=VALUES(OBSERVACIONES),ID_EVALUADO_POR=VALUES(ID_EVALUADO_POR),
    ORIGEN=VALUES(ORIGEN),ID_CAPACITACION_IMPORTACION=VALUES(ID_CAPACITACION_IMPORTACION);
    UPDATE bbf_capacitacion_participantes SET ESTADO_EVALUACION='EN_PROCESO' WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE AND ESTADO_EVALUACION='PENDIENTE';
    SELECT * FROM bbf_capacitacion_evaluaciones WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE AND ID_CAPACITACION_LABOR=P_ID_LABOR AND FECHA_EVALUACION=P_FECHA;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_RESULTADO_REGISTRAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_RESULTADO_REGISTRAR`(
    IN P_ID_PARTICIPANTE INT, IN P_FECHA_RESULTADO DATE, IN P_PUNTAJE_FINAL DECIMAL(10,2),
    IN P_PUNTAJE_MINIMO DECIMAL(10,2), IN P_RESULTADO VARCHAR(30), IN P_REQUIERE_REINDUCCION TINYINT,
    IN P_REQUIERE_COMPROMISO TINYINT, IN P_REGLA VARCHAR(500), IN P_OBSERVACIONES TEXT, IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_TOTAL DECIMAL(14,2); DECLARE V_RESULTADO VARCHAR(30);
    SELECT COALESCE(SUM(VALOR_OBTENIDO),0) INTO V_TOTAL FROM bbf_capacitacion_evaluaciones WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE;
    SET V_RESULTADO=UPPER(TRIM(IFNULL(P_RESULTADO,'')));
    IF V_RESULTADO='' THEN
        SET V_RESULTADO=CASE WHEN P_PUNTAJE_FINAL IS NULL OR P_PUNTAJE_MINIMO IS NULL THEN 'PENDIENTE'
        WHEN P_PUNTAJE_FINAL>=P_PUNTAJE_MINIMO THEN 'APROBADO' ELSE 'NO_APROBADO' END;
    END IF;
    IF V_RESULTADO NOT IN('PENDIENTE','APROBADO','NO_APROBADO','REQUIERE_REINDUCCION') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Resultado no valido.';
    END IF;
    INSERT INTO bbf_capacitacion_resultados(ID_CAPACITACION_PARTICIPANTE,FECHA_RESULTADO,TOTAL_ACUMULADO,PUNTAJE_FINAL,
    PUNTAJE_MINIMO_APLICADO,RESULTADO,REQUIERE_REINDUCCION,REQUIERE_COMPROMISO,REGLA_APLICADA,OBSERVACIONES,ID_REGISTRADO_POR)
    VALUES(P_ID_PARTICIPANTE,IFNULL(P_FECHA_RESULTADO,CURRENT_DATE),V_TOTAL,P_PUNTAJE_FINAL,P_PUNTAJE_MINIMO,V_RESULTADO,
    IFNULL(P_REQUIERE_REINDUCCION,V_RESULTADO IN('NO_APROBADO','REQUIERE_REINDUCCION')),
    IFNULL(P_REQUIERE_COMPROMISO,0),NULLIF(TRIM(P_REGLA),''),NULLIF(TRIM(P_OBSERVACIONES),''),P_ID_USUARIO)
    ON DUPLICATE KEY UPDATE FECHA_RESULTADO=VALUES(FECHA_RESULTADO),TOTAL_ACUMULADO=VALUES(TOTAL_ACUMULADO),
    PUNTAJE_FINAL=VALUES(PUNTAJE_FINAL),PUNTAJE_MINIMO_APLICADO=VALUES(PUNTAJE_MINIMO_APLICADO),RESULTADO=VALUES(RESULTADO),
    REQUIERE_REINDUCCION=VALUES(REQUIERE_REINDUCCION),REQUIERE_COMPROMISO=VALUES(REQUIERE_COMPROMISO),
    REGLA_APLICADA=VALUES(REGLA_APLICADA),OBSERVACIONES=VALUES(OBSERVACIONES),ID_REGISTRADO_POR=VALUES(ID_REGISTRADO_POR);
    UPDATE bbf_capacitacion_participantes SET ESTADO_EVALUACION=IF(V_RESULTADO='PENDIENTE','EN_PROCESO','EVALUADA')
    WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE;
    SELECT * FROM bbf_capacitacion_resultados WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_CONFIRMAR_EMPLEADO`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_CONFIRMAR_EMPLEADO`(
    IN P_ID_USUARIO INT, IN P_ID_PARTICIPANTE INT, IN P_OBSERVACION VARCHAR(500)
)
BEGIN
    DECLARE V_ID_EMPLEADO INT; DECLARE V_ID_EMPLEADO_PART INT; DECLARE V_ASISTENCIA VARCHAR(20);
    SELECT ID_EMPLEADO INTO V_ID_EMPLEADO FROM bbf_usuarios WHERE ID_USUARIO=P_ID_USUARIO AND ESTADO='ACTIVO' LIMIT 1;
    SELECT ID_EMPLEADO,ESTADO_ASISTENCIA INTO V_ID_EMPLEADO_PART,V_ASISTENCIA
    FROM bbf_capacitacion_participantes WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE LIMIT 1;
    IF V_ID_EMPLEADO IS NULL OR V_ID_EMPLEADO<>V_ID_EMPLEADO_PART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='No puede confirmar una capacitacion asociada a otro empleado.';
    END IF;
    IF V_ASISTENCIA<>'ASISTIO' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Solo puede confirmar una capacitacion con asistencia registrada.';
    END IF;
    UPDATE bbf_capacitacion_participantes SET CONFIRMO_RECIBIDO=1,FECHA_CONFIRMACION=CURRENT_TIMESTAMP,
    ID_CONFIRMADO_POR=P_ID_USUARIO,MODALIDAD_CONFIRMACION='EMPLEADO',OBSERVACION_CONFIRMACION=NULLIF(TRIM(P_OBSERVACION),'')
    WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE AND CONFIRMO_RECIBIDO=0;
    SELECT * FROM bbf_capacitacion_participantes WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_CONFIRMAR_RRHH`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_CONFIRMAR_RRHH`(
    IN P_ID_USUARIO_RRHH INT, IN P_ID_PARTICIPANTE INT, IN P_OBSERVACION VARCHAR(500)
)
BEGIN
    IF NOT EXISTS(SELECT 1 FROM bbf_usuarios WHERE ID_USUARIO=P_ID_USUARIO_RRHH AND ESTADO='ACTIVO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El usuario de RRHH no existe o esta inactivo.';
    END IF;
    IF NOT EXISTS(SELECT 1 FROM bbf_capacitacion_participantes WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE AND ESTADO_ASISTENCIA='ASISTIO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Solo se puede confirmar una capacitacion con asistencia registrada.';
    END IF;
    UPDATE bbf_capacitacion_participantes SET CONFIRMO_RECIBIDO=1,FECHA_CONFIRMACION=CURRENT_TIMESTAMP,
    ID_CONFIRMADO_POR=P_ID_USUARIO_RRHH,MODALIDAD_CONFIRMACION='PRESENCIAL_RRHH',
    OBSERVACION_CONFIRMACION=COALESCE(NULLIF(TRIM(P_OBSERVACION),''),'Confirmacion presencial registrada por Recursos Humanos.')
    WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE AND CONFIRMO_RECIBIDO=0;
    SELECT * FROM bbf_capacitacion_participantes WHERE ID_CAPACITACION_PARTICIPANTE=P_ID_PARTICIPANTE;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_SESION_DETALLE`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_SESION_DETALLE`(IN P_ID_SESION INT)
BEGIN
    SELECT S.*,C.NOMBRE AS CAPACITACION,C.TIPO,C.PUNTAJE_MINIMO,C.PUNTAJE_MAXIMO
    FROM bbf_capacitacion_sesiones S INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    WHERE S.ID_CAPACITACION_SESION=P_ID_SESION;
    SELECT P.*,E.NUMERO_DOCUMENTO,CONCAT_WS(' ',E.NOMBRES,E.APELLIDOS) AS EMPLEADO,E.ESTADO_EMPLEADO,
    R.TOTAL_ACUMULADO,R.PUNTAJE_FINAL,R.PUNTAJE_MINIMO_APLICADO,R.RESULTADO,R.REQUIERE_REINDUCCION,R.REQUIERE_COMPROMISO
    FROM bbf_capacitacion_participantes P INNER JOIN bbf_empleados E ON E.ID_EMPLEADO=P.ID_EMPLEADO
    LEFT JOIN bbf_capacitacion_resultados R ON R.ID_CAPACITACION_PARTICIPANTE=P.ID_CAPACITACION_PARTICIPANTE
    WHERE P.ID_CAPACITACION_SESION=P_ID_SESION ORDER BY E.NOMBRES,E.APELLIDOS;
    SELECT EV.*,L.CODIGO AS CODIGO_LABOR,L.NOMBRE AS LABOR,P.ID_EMPLEADO
    FROM bbf_capacitacion_evaluaciones EV
    INNER JOIN bbf_capacitacion_labores L ON L.ID_CAPACITACION_LABOR=EV.ID_CAPACITACION_LABOR
    INNER JOIN bbf_capacitacion_participantes P ON P.ID_CAPACITACION_PARTICIPANTE=EV.ID_CAPACITACION_PARTICIPANTE
    WHERE P.ID_CAPACITACION_SESION=P_ID_SESION ORDER BY P.ID_EMPLEADO,L.ORDEN,EV.FECHA_EVALUACION;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_MIS_REGISTROS_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_MIS_REGISTROS_LISTAR`(IN P_ID_USUARIO INT)
BEGIN
    SELECT P.ID_CAPACITACION_PARTICIPANTE,S.ID_CAPACITACION_SESION,S.CODIGO AS CODIGO_SESION,S.FECHA_INICIO,S.FECHA_FIN,
    S.ANIO_ISO,S.SEMANA_ISO,S.ESTADO AS ESTADO_SESION,C.ID_CAPACITACION,C.NOMBRE AS CAPACITACION,C.TIPO,
    P.ESTADO_ASISTENCIA,P.CONFIRMO_RECIBIDO,P.FECHA_CONFIRMACION,P.ESTADO_EVALUACION,
    R.PUNTAJE_FINAL,R.PUNTAJE_MINIMO_APLICADO,R.RESULTADO,R.REQUIERE_REINDUCCION,R.REQUIERE_COMPROMISO
    FROM bbf_usuarios U INNER JOIN bbf_capacitacion_participantes P ON P.ID_EMPLEADO=U.ID_EMPLEADO
    INNER JOIN bbf_capacitacion_sesiones S ON S.ID_CAPACITACION_SESION=P.ID_CAPACITACION_SESION
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    LEFT JOIN bbf_capacitacion_resultados R ON R.ID_CAPACITACION_PARTICIPANTE=P.ID_CAPACITACION_PARTICIPANTE
    WHERE U.ID_USUARIO=P_ID_USUARIO ORDER BY S.FECHA_INICIO DESC;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_ALERTAS_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_ALERTAS_LISTAR`(IN P_ID_EMPLEADO INT)
BEGIN
    SELECT 'EVALUACION_PENDIENTE' AS TIPO_ALERTA,P.ID_CAPACITACION_PARTICIPANTE,E.ID_EMPLEADO,E.NUMERO_DOCUMENTO,
    CONCAT_WS(' ',E.NOMBRES,E.APELLIDOS) AS EMPLEADO,C.NOMBRE AS CAPACITACION,S.FECHA_FIN AS FECHA_REFERENCIA,
    'La evaluacion de la capacitacion se encuentra pendiente.' AS MENSAJE
    FROM bbf_capacitacion_participantes P INNER JOIN bbf_empleados E ON E.ID_EMPLEADO=P.ID_EMPLEADO
    INNER JOIN bbf_capacitacion_sesiones S ON S.ID_CAPACITACION_SESION=P.ID_CAPACITACION_SESION
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    WHERE P.ESTADO_EVALUACION IN('PENDIENTE','EN_PROCESO') AND S.ESTADO<>'ANULADA'
      AND (P_ID_EMPLEADO IS NULL OR P_ID_EMPLEADO=0 OR E.ID_EMPLEADO=P_ID_EMPLEADO)
    UNION ALL
    SELECT 'RESULTADO_NO_APROBADO',P.ID_CAPACITACION_PARTICIPANTE,E.ID_EMPLEADO,E.NUMERO_DOCUMENTO,
    CONCAT_WS(' ',E.NOMBRES,E.APELLIDOS),C.NOMBRE,R.FECHA_RESULTADO,
    CONCAT('Resultado ',R.RESULTADO,'. Puntaje: ',COALESCE(R.PUNTAJE_FINAL,'sin definir'),'.')
    FROM bbf_capacitacion_resultados R INNER JOIN bbf_capacitacion_participantes P ON P.ID_CAPACITACION_PARTICIPANTE=R.ID_CAPACITACION_PARTICIPANTE
    INNER JOIN bbf_empleados E ON E.ID_EMPLEADO=P.ID_EMPLEADO
    INNER JOIN bbf_capacitacion_sesiones S ON S.ID_CAPACITACION_SESION=P.ID_CAPACITACION_SESION
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    WHERE R.RESULTADO IN('NO_APROBADO','REQUIERE_REINDUCCION')
      AND (P_ID_EMPLEADO IS NULL OR P_ID_EMPLEADO=0 OR E.ID_EMPLEADO=P_ID_EMPLEADO)
    ORDER BY FECHA_REFERENCIA DESC;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_COMPROMISO_CREAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_COMPROMISO_CREAR`(
    IN P_ID_RESULTADO INT, IN P_FECHA DATE, IN P_FECHA_LIMITE DATE, IN P_MOTIVO TEXT,
    IN P_COMPROMISOS TEXT, IN P_OBSERVACIONES TEXT, IN P_ID_USUARIO INT
)
BEGIN
    IF NOT EXISTS(SELECT 1 FROM bbf_capacitacion_resultados WHERE ID_CAPACITACION_RESULTADO=P_ID_RESULTADO AND RESULTADO IN('NO_APROBADO','REQUIERE_REINDUCCION')) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Solo se puede generar compromiso para un resultado no aprobado.';
    END IF;
    INSERT INTO bbf_capacitacion_compromisos(ID_CAPACITACION_RESULTADO,FECHA_COMPROMISO,FECHA_LIMITE,MOTIVO,
    COMPROMISOS_EMPLEADO,ESTADO,OBSERVACIONES,ID_CREADO_POR)
    VALUES(P_ID_RESULTADO,IFNULL(P_FECHA,CURRENT_DATE),P_FECHA_LIMITE,TRIM(P_MOTIVO),NULLIF(TRIM(P_COMPROMISOS),''),'BORRADOR',
    NULLIF(TRIM(P_OBSERVACIONES),''),P_ID_USUARIO);
    UPDATE bbf_capacitacion_resultados SET REQUIERE_COMPROMISO=1 WHERE ID_CAPACITACION_RESULTADO=P_ID_RESULTADO;
    SELECT * FROM bbf_capacitacion_compromisos WHERE ID_CAPACITACION_COMPROMISO=LAST_INSERT_ID();
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_COMPROMISO_ACTUALIZAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_COMPROMISO_ACTUALIZAR`(
    IN P_ID_COMPROMISO INT, IN P_ESTADO VARCHAR(30), IN P_DOCUMENTO_URL VARCHAR(500),
    IN P_DOCUMENTO_RUTA VARCHAR(500), IN P_FIRMA_URL VARCHAR(500), IN P_OBSERVACIONES TEXT, IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_ESTADO VARCHAR(30); SET V_ESTADO=UPPER(TRIM(P_ESTADO));
    IF V_ESTADO NOT IN('BORRADOR','PENDIENTE_FIRMA','FIRMADO','CUMPLIDO','INCUMPLIDO','ANULADO') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Estado de compromiso no valido.';
    END IF;
    UPDATE bbf_capacitacion_compromisos SET ESTADO=V_ESTADO,DOCUMENTO_URL=NULLIF(TRIM(P_DOCUMENTO_URL),''),
    DOCUMENTO_RUTA=NULLIF(TRIM(P_DOCUMENTO_RUTA),''),FIRMA_URL=NULLIF(TRIM(P_FIRMA_URL),''),
    FECHA_FIRMA=CASE WHEN V_ESTADO IN('FIRMADO','CUMPLIDO','INCUMPLIDO') AND FECHA_FIRMA IS NULL THEN CURRENT_TIMESTAMP ELSE FECHA_FIRMA END,
    ID_CERRADO_POR=CASE WHEN V_ESTADO IN('CUMPLIDO','INCUMPLIDO','ANULADO') THEN P_ID_USUARIO ELSE ID_CERRADO_POR END,
    OBSERVACIONES=COALESCE(NULLIF(TRIM(P_OBSERVACIONES),''),OBSERVACIONES) WHERE ID_CAPACITACION_COMPROMISO=P_ID_COMPROMISO;
    SELECT * FROM bbf_capacitacion_compromisos WHERE ID_CAPACITACION_COMPROMISO=P_ID_COMPROMISO;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_COMPROMISOS_LISTAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_COMPROMISOS_LISTAR`(IN P_ID_EMPLEADO INT, IN P_ESTADO VARCHAR(30))
BEGIN
    SELECT CO.*,R.RESULTADO,R.PUNTAJE_FINAL,R.PUNTAJE_MINIMO_APLICADO,E.ID_EMPLEADO,E.NUMERO_DOCUMENTO,
    CONCAT_WS(' ',E.NOMBRES,E.APELLIDOS) AS EMPLEADO,C.NOMBRE AS CAPACITACION,S.FECHA_INICIO,S.FECHA_FIN
    FROM bbf_capacitacion_compromisos CO INNER JOIN bbf_capacitacion_resultados R ON R.ID_CAPACITACION_RESULTADO=CO.ID_CAPACITACION_RESULTADO
    INNER JOIN bbf_capacitacion_participantes P ON P.ID_CAPACITACION_PARTICIPANTE=R.ID_CAPACITACION_PARTICIPANTE
    INNER JOIN bbf_empleados E ON E.ID_EMPLEADO=P.ID_EMPLEADO
    INNER JOIN bbf_capacitacion_sesiones S ON S.ID_CAPACITACION_SESION=P.ID_CAPACITACION_SESION
    INNER JOIN bbf_capacitaciones C ON C.ID_CAPACITACION=S.ID_CAPACITACION
    WHERE (P_ID_EMPLEADO IS NULL OR P_ID_EMPLEADO=0 OR E.ID_EMPLEADO=P_ID_EMPLEADO)
      AND (NULLIF(TRIM(P_ESTADO),'') IS NULL OR CO.ESTADO=UPPER(TRIM(P_ESTADO)))
    ORDER BY CO.FECHA_COMPROMISO DESC;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_IMPORTACION_CREAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_IMPORTACION_CREAR`(
    IN P_ID_SESION INT, IN P_NOMBRE_ARCHIVO VARCHAR(255), IN P_NOMBRE_ORIGINAL VARCHAR(255),
    IN P_RUTA VARCHAR(500), IN P_MIME VARCHAR(100), IN P_PESO BIGINT, IN P_ID_USUARIO INT
)
BEGIN
    INSERT INTO bbf_capacitacion_importaciones(ID_CAPACITACION_SESION,NOMBRE_ARCHIVO,NOMBRE_ORIGINAL,ARCHIVO_RUTA,MIME_TYPE,PESO_BYTES,ID_CARGADO_POR)
    VALUES(P_ID_SESION,TRIM(P_NOMBRE_ARCHIVO),TRIM(P_NOMBRE_ORIGINAL),TRIM(P_RUTA),NULLIF(TRIM(P_MIME),''),P_PESO,P_ID_USUARIO);
    SELECT * FROM bbf_capacitacion_importaciones WHERE ID_CAPACITACION_IMPORTACION=LAST_INSERT_ID();
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_IMPORTACION_ERROR_AGREGAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_IMPORTACION_ERROR_AGREGAR`(
    IN P_ID_IMPORTACION BIGINT, IN P_HOJA VARCHAR(150), IN P_CELDA VARCHAR(30), IN P_FILA INT,
    IN P_EMPLEADO VARCHAR(250), IN P_LABOR VARCHAR(250), IN P_VALOR VARCHAR(500), IN P_CODIGO VARCHAR(80), IN P_MENSAJE VARCHAR(500)
)
BEGIN
    INSERT INTO bbf_capacitacion_importacion_errores(ID_CAPACITACION_IMPORTACION,HOJA,CELDA,FILA,EMPLEADO_ORIGINAL,LABOR_ORIGINAL,VALOR_ORIGINAL,CODIGO_ERROR,MENSAJE)
    VALUES(P_ID_IMPORTACION,NULLIF(TRIM(P_HOJA),''),NULLIF(TRIM(P_CELDA),''),P_FILA,NULLIF(TRIM(P_EMPLEADO),''),NULLIF(TRIM(P_LABOR),''),
    NULLIF(TRIM(P_VALOR),''),UPPER(TRIM(P_CODIGO)),TRIM(P_MENSAJE));
    UPDATE bbf_capacitacion_importaciones SET TOTAL_ERRORES=TOTAL_ERRORES+1,ESTADO='CON_ERRORES' WHERE ID_CAPACITACION_IMPORTACION=P_ID_IMPORTACION;
END$$

DROP PROCEDURE IF EXISTS `SP_BBF_CAPACITACION_IMPORTACION_FINALIZAR`$$
CREATE PROCEDURE `SP_BBF_CAPACITACION_IMPORTACION_FINALIZAR`(
    IN P_ID_IMPORTACION BIGINT, IN P_ESTADO VARCHAR(20), IN P_TOTAL INT, IN P_VALIDOS INT, IN P_RESUMEN TEXT
)
BEGIN
    DECLARE V_ESTADO VARCHAR(20); SET V_ESTADO=UPPER(TRIM(P_ESTADO));
    IF V_ESTADO NOT IN('CON_ERRORES','VALIDADA','IMPORTADA','ANULADA') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Estado de importacion no valido.'; END IF;
    UPDATE bbf_capacitacion_importaciones SET ESTADO=V_ESTADO,TOTAL_REGISTROS=IFNULL(P_TOTAL,0),TOTAL_VALIDOS=IFNULL(P_VALIDOS,0),
    TOTAL_ERRORES=(SELECT COUNT(*) FROM bbf_capacitacion_importacion_errores WHERE ID_CAPACITACION_IMPORTACION=P_ID_IMPORTACION),
    RESUMEN=P_RESUMEN,FECHA_IMPORTACION=CASE WHEN V_ESTADO='IMPORTADA' THEN CURRENT_TIMESTAMP ELSE FECHA_IMPORTACION END
    WHERE ID_CAPACITACION_IMPORTACION=P_ID_IMPORTACION;
    SELECT * FROM bbf_capacitacion_importaciones WHERE ID_CAPACITACION_IMPORTACION=P_ID_IMPORTACION;
END$$

DELIMITER ;

-- ============================================================================
-- 5. VALIDACIONES POSTERIORES
-- ============================================================================

SELECT COUNT(*) AS TOTAL_TABLAS_CAPACITACIONES
FROM information_schema.TABLES
WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME LIKE 'bbf_capacitacion%';

SELECT COUNT(*) AS TOTAL_PROCEDIMIENTOS_CAPACITACIONES
FROM information_schema.ROUTINES
WHERE ROUTINE_SCHEMA=DATABASE() AND ROUTINE_TYPE='PROCEDURE'
  AND ROUTINE_NAME LIKE 'SP_BBF_CAPACITACION%';

SELECT CODIGO,NOMBRE,ACTIVO FROM bbf_capacitacion_labores ORDER BY ORDEN;
SELECT ID_CAPACITACION,CODIGO,NOMBRE,TIPO,PUNTAJE_MINIMO,PUNTAJE_MAXIMO,ACTIVO FROM bbf_capacitaciones;
SELECT CODIGO,NOMBRE,MODULO,ACTIVO FROM bbf_permisos WHERE CODIGO LIKE 'CAPACITACIONES_%' ORDER BY CODIGO;

-- Resultado esperado en instalacion nueva:
-- TOTAL_TABLAS_CAPACITACIONES = 11
-- TOTAL_PROCEDIMIENTOS_CAPACITACIONES = 22
-- 12 labores iniciales
-- 1 capacitacion base
-- 7 permisos
