DELIMITER $$

DROP PROCEDURE IF EXISTS SP_BBF_HERRAMIENTAS_EMPLEADO_USUARIO_OBTENER$$
CREATE PROCEDURE SP_BBF_HERRAMIENTAS_EMPLEADO_USUARIO_OBTENER(
    IN P_ID_USUARIO INT
)
BEGIN
    SELECT E.ID_EMPLEADO
    FROM bbf_usuarios U
    INNER JOIN bbf_empleados E ON E.ID_EMPLEADO = U.ID_EMPLEADO
    WHERE U.ID_USUARIO = P_ID_USUARIO
      AND IFNULL(E.ELIMINADO, 0) = 0
    LIMIT 1;
END$$

DROP PROCEDURE IF EXISTS SP_BBF_HERRAMIENTAS_MIS_ENTREGAS_LISTAR$$
CREATE PROCEDURE SP_BBF_HERRAMIENTAS_MIS_ENTREGAS_LISTAR(
    IN P_ID_EMPLEADO INT
)
BEGIN
    SELECT
        HE.ID_ENTREGA,
        HE.FECHA_ENTREGA,
        HE.ESTADO,
        HE.OBSERVACIONES,
        HE.FECHA_CONFIRMACION,
        COALESCE(SUM(HD.CANTIDAD), 0) AS TOTAL_HERRAMIENTAS
    FROM bbf_herramientas_entregas HE
    LEFT JOIN bbf_herramientas_entrega_detalle HD
        ON HD.ID_ENTREGA = HE.ID_ENTREGA
    WHERE HE.ID_EMPLEADO = P_ID_EMPLEADO
    GROUP BY
        HE.ID_ENTREGA,
        HE.FECHA_ENTREGA,
        HE.ESTADO,
        HE.OBSERVACIONES,
        HE.FECHA_CONFIRMACION
    ORDER BY HE.FECHA_ENTREGA DESC, HE.ID_ENTREGA DESC;
END$$

DROP PROCEDURE IF EXISTS SP_BBF_HERRAMIENTAS_MI_ENTREGA_OBTENER$$
CREATE PROCEDURE SP_BBF_HERRAMIENTAS_MI_ENTREGA_OBTENER(
    IN P_ID_ENTREGA INT,
    IN P_ID_EMPLEADO INT
)
BEGIN
    SELECT
        HE.ID_ENTREGA,
        HE.FECHA_ENTREGA,
        HE.ESTADO,
        HE.OBSERVACIONES,
        HE.FECHA_CONFIRMACION,
        HE.CREATED_AT,
        HE.UPDATED_AT
    FROM bbf_herramientas_entregas HE
    WHERE HE.ID_ENTREGA = P_ID_ENTREGA
      AND HE.ID_EMPLEADO = P_ID_EMPLEADO
    LIMIT 1;
END$$

DROP PROCEDURE IF EXISTS SP_BBF_HERRAMIENTAS_MI_ENTREGA_DETALLE_LISTAR$$
CREATE PROCEDURE SP_BBF_HERRAMIENTAS_MI_ENTREGA_DETALLE_LISTAR(
    IN P_ID_ENTREGA INT,
    IN P_ID_EMPLEADO INT
)
BEGIN
    SELECT
        HD.ID_DETALLE,
        HD.ID_HERRAMIENTA,
        H.NOMBRE AS HERRAMIENTA,
        HD.CANTIDAD,
        HD.OBSERVACIONES
    FROM bbf_herramientas_entrega_detalle HD
    INNER JOIN bbf_herramientas_entregas HE
        ON HE.ID_ENTREGA = HD.ID_ENTREGA
       AND HE.ID_EMPLEADO = P_ID_EMPLEADO
    INNER JOIN bbf_herramientas H
        ON H.ID_HERRAMIENTA = HD.ID_HERRAMIENTA
    WHERE HD.ID_ENTREGA = P_ID_ENTREGA
    ORDER BY HD.ID_DETALLE;
END$$

DROP PROCEDURE IF EXISTS SP_BBF_HERRAMIENTAS_MI_ENTREGA_CONFIRMAR$$
CREATE PROCEDURE SP_BBF_HERRAMIENTAS_MI_ENTREGA_CONFIRMAR(
    IN P_ID_ENTREGA INT,
    IN P_ID_EMPLEADO INT,
    IN P_ID_USUARIO INT
)
BEGIN
    DECLARE V_ESTADO VARCHAR(20);

    SELECT HE.ESTADO
    INTO V_ESTADO
    FROM bbf_herramientas_entregas HE
    WHERE HE.ID_ENTREGA = P_ID_ENTREGA
      AND HE.ID_EMPLEADO = P_ID_EMPLEADO
    LIMIT 1;

    IF V_ESTADO IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'La entrega de herramientas no existe.';
    END IF;

    IF LOWER(V_ESTADO) = 'confirmada' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'La entrega de herramientas ya fue confirmada.';
    END IF;

    UPDATE bbf_herramientas_entregas
    SET ESTADO = 'confirmada',
        FECHA_CONFIRMACION = NOW(),
        UPDATED_AT = NOW()
    WHERE ID_ENTREGA = P_ID_ENTREGA
      AND ID_EMPLEADO = P_ID_EMPLEADO;

    SELECT
        ID_ENTREGA,
        ESTADO,
        FECHA_CONFIRMACION,
        P_ID_USUARIO AS ID_USUARIO_CONFIRMACION
    FROM bbf_herramientas_entregas
    WHERE ID_ENTREGA = P_ID_ENTREGA
      AND ID_EMPLEADO = P_ID_EMPLEADO;
END$$

DELIMITER ;
