DROP PROCEDURE IF EXISTS SP_BBF_TIPOS_DOCUMENTO_LISTAR;

DELIMITER $$

CREATE PROCEDURE SP_BBF_TIPOS_DOCUMENTO_LISTAR(IN P_SOLO_ACTIVOS TINYINT)
BEGIN
    SELECT
        ID_TIPO_DOCUMENTO,
        NOMBRE,
        ACTIVO,
        CREATED_AT,
        UPDATED_AT
    FROM BBF_TIPOS_DOCUMENTO
    WHERE COALESCE(P_SOLO_ACTIVOS, 1) = 0
        OR ACTIVO = 1
    ORDER BY NOMBRE;
END$$

DELIMITER ;
