import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize } from 'rxjs/operators';
import { Observable } from 'rxjs';
import { DepartmentParameter, MunicipalityParameter } from '../../core/models/api.models';
import { AuthService } from '../../core/services/auth.service';
import { ParametersService } from '../../core/services/parameters.service';
import { apiErrorMessage } from '../../shared/api-error';

@Component({standalone:true,imports:[FormsModule],styles:[`
  .geo-layout{display:grid;grid-template-columns:minmax(280px,360px) minmax(0,1fr);gap:1rem;align-items:start}.geo-panel{padding:0;overflow:hidden}.geo-head{padding:1.25rem;border-bottom:1px solid var(--border-color,#dbe4df);display:flex;justify-content:space-between;align-items:center;gap:1rem}.geo-head h2{margin:0;font-size:1.12rem}.geo-head p{margin:.2rem 0 0;color:#687871}.department-tools{padding:1rem;border-bottom:1px solid var(--border-color,#dbe4df)}.search-field{position:relative;display:block}.search-field input{width:100%;padding-left:2.35rem}.search-icon{position:absolute;left:.85rem;top:50%;transform:translateY(-50%);color:#6d7d76}.department-list{list-style:none;margin:0;padding:.45rem;max-height:64vh;overflow:auto}.department-item{display:grid;grid-template-columns:1fr auto;gap:.65rem;padding:.85rem;border-radius:10px;border:1px solid transparent;margin:.2rem 0;cursor:pointer;transition:.16s;background:transparent}.department-item:hover{background:#f3f8f5}.department-item.active{background:#e8f4ee;border-color:#bcd9ca;box-shadow:inset 3px 0 #0e6046}.department-title{display:flex;gap:.65rem;align-items:flex-start}.dane-chip{font-size:.72rem;font-weight:800;letter-spacing:.08em;background:#eef2f0;border-radius:7px;padding:.3rem .42rem;min-width:2.4rem;text-align:center}.department-name{font-weight:750;line-height:1.25}.department-meta{font-size:.77rem;color:#71817a;margin-top:.22rem}.row-actions{display:flex;align-items:center;gap:.25rem}.icon-action{border:0;background:transparent;border-radius:7px;padding:.35rem;color:#36544a;cursor:pointer}.icon-action:hover{background:#dcebe4}.municipality-tools{display:grid;grid-template-columns:minmax(200px,1fr) auto;gap:.75rem;padding:1rem 1.25rem}.municipality-table{padding:0 1.25rem 1.25rem}.status-dot{display:inline-block;width:.48rem;height:.48rem;border-radius:50%;background:#9ba8a2;margin-right:.4rem}.status-dot.on{background:#159064}.empty-state{text-align:center;padding:3rem 1rem;color:#71817a}.count-pill{background:#edf5f1;color:#145d46;border-radius:999px;padding:.32rem .65rem;font-size:.78rem;font-weight:750}@media(max-width:900px){.geo-layout{grid-template-columns:1fr}.department-list{max-height:340px}.municipality-tools{grid-template-columns:1fr}}
`],template:`
<div class="page-heading"><div><p class="eyebrow">Parámetros</p><h1>Departamentos y municipios</h1><p>Administra la división geográfica usada en aspirantes y empleados.</p></div></div>
@if(error()){<div class="alert error">{{error()}}</div>}
<div class="geo-layout"><section class="panel geo-panel"><div class="geo-head"><div><h2>Departamentos</h2><p>{{departments().length}} registrados</p></div>@if(auth.hasPermission('PARAMETROS_ADMINISTRAR')){<button class="btn primary" (click)="editDepartment()">+ Agregar</button>}</div>
<div class="department-tools"><label class="search-field"><span class="search-icon">⌕</span><input [(ngModel)]="departmentSearch" placeholder="Buscar departamento" aria-label="Buscar departamento" /></label></div><ul class="department-list">
@for(d of filteredDepartments();track d.id_departamento){<li class="department-item" [class.active]="selectedDepartment()===d.id_departamento" (click)="selectDepartment(d)"><div class="department-title"><span class="dane-chip">{{d.codigo_dane}}</span><div><div class="department-name">{{d.nombre}}</div><div class="department-meta"><span class="status-dot" [class.on]="d.activo"></span>{{d.activo?'Activo':'Inactivo'}} · {{d.municipios_activos}} municipios activos</div></div></div>@if(auth.hasPermission('PARAMETROS_ADMINISTRAR')){<div class="row-actions"><button class="icon-action" title="Editar" (click)="$event.stopPropagation();editDepartment(d)">✎</button><button class="icon-action" [title]="d.activo?'Inactivar':'Activar'" (click)="$event.stopPropagation();toggleDepartment(d)">{{d.activo?'○':'●'}}</button></div>}</li>}@empty{<li class="empty-state">No se encontraron departamentos.</li>}
</ul></section>
<section class="panel geo-panel"><div class="geo-head"><div><h2>{{selectedDepartmentName()||'Municipios'}}</h2><p>Municipios asociados al departamento</p></div><span class="count-pill">{{filteredMunicipalities().length}} municipios</span></div>
<div class="municipality-tools"><label class="search-field"><span class="search-icon">⌕</span><input [(ngModel)]="search" placeholder="Buscar por nombre o código DANE" aria-label="Buscar municipio" /></label>@if(selectedDepartment()&&auth.hasPermission('PARAMETROS_ADMINISTRAR')){<button class="btn primary" (click)="editMunicipality()">+ Agregar municipio</button>}</div><div class="table-wrap municipality-table"><table><thead><tr><th>Código DANE</th><th>Municipio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
@for(m of filteredMunicipalities();track m.id_municipio){<tr><td>{{m.codigo_dane}}</td><td><strong>{{m.nombre}}</strong></td><td><span class="badge" [class.success]="m.activo">{{m.activo?'ACTIVO':'INACTIVO'}}</span></td><td>@if(auth.hasPermission('PARAMETROS_ADMINISTRAR')){<button class="btn small" (click)="editMunicipality(m)">Editar</button> <button class="btn small secondary" (click)="toggleMunicipality(m)">{{m.activo?'Inactivar':'Activar'}}</button>}</td></tr>}@empty{<tr><td colspan="4" class="empty">No hay municipios para mostrar.</td></tr>}
</tbody></table></div></section></div>
@if(modal()){<section class="panel modal"><div class="modal-content"><header><h2>{{editingId?'Editar':'Agregar'}} {{mode==='department'?'departamento':'municipio'}}</h2><button class="icon-btn" (click)="modal.set(false)">×</button></header><form (ngSubmit)="save()">
<label>Código DANE *<input [(ngModel)]="formCode" name="code" inputmode="numeric" [maxlength]="mode==='department'?2:5" required /></label><label>Nombre *<input [(ngModel)]="formName" name="name" maxlength="150" required /></label>
@if(formError()){<div class="alert error">{{formError()}}</div>}<div class="modal-actions"><button type="button" class="btn secondary" (click)="modal.set(false)">Cancelar</button><button class="btn primary" [disabled]="loading()">{{loading()?'Guardando…':'Guardar'}}</button></div></form></div></section>}
`})
export class ParametersGeographyComponent implements OnInit{
 private readonly service=inject(ParametersService); readonly auth=inject(AuthService); readonly departments=signal<DepartmentParameter[]>([]); readonly municipalities=signal<MunicipalityParameter[]>([]); readonly selectedDepartment=signal<number|null>(null); readonly error=signal(''); readonly modal=signal(false); readonly loading=signal(false); readonly formError=signal(''); search='';departmentSearch=''; mode:'department'|'municipality'='department'; editingId:number|null=null; formCode='';formName='';active=true;
 ngOnInit(){this.loadDepartments();} selectedDepartmentName(){return this.departments().find(d=>d.id_departamento===this.selectedDepartment())?.nombre??'';} filteredDepartments(){const q=this.departmentSearch.trim().toLowerCase();return this.departments().filter(d=>!q||d.nombre.toLowerCase().includes(q)||d.codigo_dane.includes(q));} filteredMunicipalities(){const q=this.search.trim().toLowerCase();return this.municipalities().filter(m=>!q||m.nombre.toLowerCase().includes(q)||m.codigo_dane.includes(q));}
 loadDepartments(){this.service.listDepartments().subscribe({next:rows=>{this.departments.set(rows);if(!this.selectedDepartment()&&rows.length)this.selectDepartment(rows.find(x=>x.activo)??rows[0]);},error:e=>this.error.set(apiErrorMessage(e,'No fue posible cargar los departamentos.'))});}
 selectDepartment(d:DepartmentParameter){this.selectedDepartment.set(d.id_departamento);this.search='';this.service.listMunicipalities(d.id_departamento).subscribe({next:r=>this.municipalities.set(r),error:e=>this.error.set(apiErrorMessage(e,'No fue posible cargar los municipios.'))});}
 editDepartment(d?:DepartmentParameter){this.mode='department';this.editingId=d?.id_departamento??null;this.formCode=d?.codigo_dane??'';this.formName=d?.nombre??'';this.active=d?.activo??true;this.formError.set('');this.modal.set(true);}
 editMunicipality(m?:MunicipalityParameter){this.mode='municipality';this.editingId=m?.id_municipio??null;this.formCode=m?.codigo_dane??'';this.formName=m?.nombre??'';this.active=m?.activo??true;this.formError.set('');this.modal.set(true);}
 save(){const digits=this.mode==='department'?2:5;if(!new RegExp(`^\\d{${digits}}$`).test(this.formCode)||!this.formName.trim()){this.formError.set(`Ingresa un código DANE de ${digits} dígitos y un nombre.`);return;}this.loading.set(true);const payload:any={codigo_dane:this.formCode,nombre:this.formName.trim(),activo:this.active};let op:Observable<unknown>;if(this.mode==='department')op=this.editingId?this.service.updateDepartment(this.editingId,payload):this.service.createDepartment(payload);else{payload.id_departamento=this.selectedDepartment();op=this.editingId?this.service.updateMunicipality(this.editingId,payload):this.service.createMunicipality(payload);}op.pipe(finalize(()=>this.loading.set(false))).subscribe({next:()=>{this.modal.set(false);this.loadDepartments();const d=this.departments().find(x=>x.id_departamento===this.selectedDepartment());if(d)this.selectDepartment(d);},error:(e:unknown)=>this.formError.set(apiErrorMessage(e,'No fue posible guardar.'))});}
 toggleDepartment(d:DepartmentParameter){if(d.activo&&!confirm(`¿Inactivar ${d.nombre}?`))return;this.service.updateDepartment(d.id_departamento,{codigo_dane:d.codigo_dane,nombre:d.nombre,activo:!d.activo}).subscribe({next:()=>this.loadDepartments(),error:e=>this.error.set(apiErrorMessage(e,'No fue posible cambiar el estado.'))});}
 toggleMunicipality(m:MunicipalityParameter){this.service.updateMunicipality(m.id_municipio,{id_departamento:m.id_departamento,codigo_dane:m.codigo_dane,nombre:m.nombre,activo:!m.activo}).subscribe({next:()=>{const d=this.departments().find(x=>x.id_departamento===m.id_departamento);if(d)this.selectDepartment(d);},error:e=>this.error.set(apiErrorMessage(e,'No fue posible cambiar el estado.'))});}
}
